/* adapted from https://github.com/gcanti/retry-ts */
export { applyAndDelay } from "./applyAndDelay"
export { applyPolicy } from "./applyPolicy"
export { capDelay } from "./capDelay"
export { constantDelay } from "./constantDelay"
export { defaultRetryStatus } from "./defaultRetryStatus"
export { exponentialBackoff } from "./exponentialBackoff"
export { limitRetries } from "./limitRetries"
export { limitRetriesByDelay } from "./limitRetriesByDelay"
export { monoidRetryPolicy } from "./monoidRetryPolicy"
export { retrying } from "./retrying"
export type { RetryPolicy } from "./RetryPolicy"
export type { RetryStatus } from "./RetryStatus"
