/**
 * Per-file output the snapshot sets don't exercise (EFF-1831): stale-file
 * detection, fragment declaration order, inlining an overlapping fragment and
 * appending fragments reached through other fragments to the document.
 */
import * as NodeServices from "@effect/platform-node/NodeServices"
import { assert, describe, it } from "@effect/vitest"
import * as Effect from "effect/Effect"
import * as FileSystem from "effect/FileSystem"
import * as Path from "effect/Path"
import {
  assertDeclaredInOrder,
  assertNoErrors,
  documentOf,
  generateIn,
  generateTasks,
  member
} from "./utils/generator.ts"

// `TaskSchedule` is defined before the `TaskCore` it spreads, so source order
// and dependency order disagree.
const fragments = `
fragment TaskSchedule on Task {
  due
  ...TaskCore
}

fragment TaskCore on Task {
  id
  title
}
`

const tasks = `
query Scheduled {
  tasks {
    ...TaskSchedule
  }
}

query Titled {
  tasks {
    ...TaskCore
    title
    done
  }
}
`

const generate = generateTasks({ "src/fragments.graphql": fragments, "src/tasks.graphql": tasks }).pipe(
  Effect.map((generated) => {
    assertNoErrors(generated)
    return { fragments: generated.file("src/fragments.graphql.ts"), tasks: generated.file("src/tasks.graphql.ts") }
  })
)

describe("Generator per-file output", () => {
  it.effect("deletes lists only headered orphans, not handwritten files, live outputs or the shared module", () =>
    Effect.gen(function*() {
      const orphan =
        "// Generated by @effect/graphql-generator from orphan.graphql. Do not edit.\nexport const Orphan = 1\n"
      const generated = yield* generateIn({
        "schema.graphql": "type Query { hello: String! }",
        "src/live.graphql": "query Live { hello }",
        "src/live.graphql.ts": "// Generated by @effect/graphql-generator from live.graphql. Do not edit.\n",
        "src/orphan.graphql.ts": orphan,
        "src/handwritten.graphql.ts": "export const Handwritten = true\n",
        "src/shared.graphql.ts": "// Generated by @effect/graphql-generator from schema.graphql. Do not edit.\n"
      }, {
        schema: "./schema.graphql",
        documents: ["src/**/*.graphql"],
        shared: "./src/shared.graphql.ts"
      })
      assertNoErrors(generated)
      const path = yield* Path.Path
      assert.deepStrictEqual(generated.result.deletes.map((file) => path.basename(file)), ["orphan.graphql.ts"])
      const fs = yield* FileSystem.FileSystem
      assert.strictEqual(yield* fs.readFileString(generated.result.deletes[0]!), orphan)
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("fragments are declared after the fragments they spread", () =>
    Effect.gen(function*() {
      const { fragments } = yield* generate
      assertDeclaredInOrder(fragments, ["TaskCore", "TaskSchedule"])
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("a fragment whose keys overlap its siblings is written out inline", () =>
    Effect.gen(function*() {
      const { tasks } = yield* generate
      assert.notInclude(tasks, "...TaskCore.fields")
      assert.strictEqual(member(tasks, "id"), "Shared.ID")
      assert.strictEqual(member(tasks, "title"), "Schema.String")
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("documents append every fragment they use, including through other fragments, in order of first use", () =>
    Effect.gen(function*() {
      const { tasks } = yield* generate
      assert.strictEqual(
        documentOf(tasks, "Scheduled"),
        "query Scheduled{tasks{...TaskSchedule}}fragment TaskSchedule on Task{due...TaskCore}fragment TaskCore on Task{id title}"
      )
    }).pipe(Effect.provide(NodeServices.layer)))
})
