/**
 * Per-file output (EFF-1831 points 1, 2, 3, 5, 7 and 9): exports, groups,
 * fragment reuse, cross-file imports and the compact document string. The
 * byte-for-byte snapshots of the GitHub set are a separate test.
 */
import * as NodeServices from "@effect/platform-node/NodeServices"
import { assert, describe, it } from "@effect/vitest"
import * as Effect from "effect/Effect"
import {
  assertDeclaredInOrder,
  assertNoErrors,
  declaration,
  declares,
  documentOf,
  fileLines,
  generateGitHub,
  generateTasks,
  member,
  members,
  warnings
} from "./utils/generator.ts"

// `TaskSchedule` is defined before the `TaskCore` it spreads, so source order
// and dependency order disagree.
const fragments = `
fragment TaskSchedule on Task {
  due
  ...TaskCore
}

fragment TaskCore on Task {
  id
  title
}
`

const tasks = `
query OneTask($taskId: ID!) {
  one: task(id: $taskId) {
    ...TaskCore
  }
}

query Scheduled {
  scheduled: tasks {
    ...TaskSchedule
    estimate
  }
}

query Titled {
  titled: tasks {
    ...TaskCore
    title
    done
  }
}

query Both($taskId: ID!) {
  core: task(id: $taskId) {
    ...TaskCore
  }
  later: tasks {
    ...TaskSchedule
    estimate
  }
}
`

const generate = generateTasks({ "src/fragments.graphql": fragments, "src/tasks.graphql": tasks }).pipe(
  Effect.map((generated) => {
    assertNoErrors(generated)
    return {
      fragments: generated.file("src/fragments.graphql.ts"),
      tasks: generated.file("src/tasks.graphql.ts"),
      generated
    }
  })
)

const groupDeclaration = /^export const \w+Group\b/

describe("Generator per-file output", () => {
  it.effect("each .graphql file generates a sibling .graphql.ts", () =>
    Effect.gen(function*() {
      const { generated } = yield* generate
      assert.deepStrictEqual(generated.paths, [
        "schema/app.graphql.ts",
        "src/fragments.graphql.ts",
        "src/tasks.graphql.ts"
      ])
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("every generated file starts with the header", () =>
    Effect.gen(function*() {
      const { fragments, generated, tasks } = yield* generate
      assert.match(
        fileLines(fragments)[0]!,
        /^\/\/ Generated by @effect\/graphql-generator from (?:.*\/)?fragments\.graphql\. Do not edit\.$/
      )
      assert.match(
        fileLines(tasks)[0]!,
        /^\/\/ Generated by @effect\/graphql-generator from (?:.*\/)?tasks\.graphql\. Do not edit\.$/
      )
      assert.strictEqual(
        fileLines(generated.file("schema/app.graphql.ts"))[0],
        "// Generated by @effect/graphql-generator. Do not edit."
      )
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("one operation value and a type-only namespace per operation, and one group named after the file", () =>
    Effect.gen(function*() {
      const { tasks } = yield* generate
      const lines = fileLines(tasks)
      assert.include(lines, `export const OneTask = GraphQL.query("OneTask", {`)
      assert.include(lines, "export declare namespace OneTask {")
      assert.isTrue(lines.some((line) => line.startsWith("export type Variables = ")))
      assert.isTrue(lines.some((line) => line.startsWith("export type Result = ")))
      assert.include(lines, "export const TasksGroup = GraphQLGroup.make(OneTask, Scheduled, Titled, Both)")
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("a fragment-only file exports one Opaque class per fragment and no group", () =>
    Effect.gen(function*() {
      const { fragments } = yield* generate
      assert.match(declaration(fragments, "TaskCore"), /^export class TaskCore extends Schema\.Opaque<TaskCore>\(\)\(/)
      assert.match(
        declaration(fragments, "TaskSchedule"),
        /^export class TaskSchedule extends Schema\.Opaque<TaskSchedule>\(\)\(/
      )
      assert.isFalse(fileLines(fragments).some((line) => groupDeclaration.test(line)))
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("fragments are declared after the fragments they spread", () =>
    Effect.gen(function*() {
      const { fragments } = yield* generate
      assertDeclaredInOrder(fragments, ["TaskCore", "TaskSchedule"])
      assert.include(fileLines(fragments).map((line) => line.replace(/,$/, "")), "...TaskCore.fields")
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("a selection that is only a spread references the fragment", () =>
    Effect.gen(function*() {
      const { tasks } = yield* generate
      assert.strictEqual(member(tasks, "one"), "Schema.NullOr(TaskCore)")
      assert.strictEqual(member(tasks, "core"), "Schema.NullOr(TaskCore)")
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("a fragment whose keys don't overlap its siblings is spread with .fields", () =>
    Effect.gen(function*() {
      const { tasks } = yield* generate
      assert.strictEqual(member(tasks, "scheduled"), "Schema.Array(Schema.Struct({")
      const spreads = fileLines(tasks).filter((line) => line.replace(/,$/, "") === "...TaskSchedule.fields")
      assert.strictEqual(spreads.length, 2)
      assert.deepStrictEqual(members(tasks, "estimate"), ["Schema.NullOr(Shared.Float)", "Schema.NullOr(Shared.Float)"])
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("a fragment whose keys overlap its siblings is written out inline", () =>
    Effect.gen(function*() {
      const { tasks } = yield* generate
      assert.isFalse(fileLines(tasks).some((line) => line.startsWith("...TaskCore.fields")))
      assert.strictEqual(member(tasks, "titled"), "Schema.Array(Schema.Struct({")
      assert.strictEqual(member(tasks, "id"), "Shared.ID")
      assert.strictEqual(member(tasks, "title"), "Schema.String")
      assert.strictEqual(member(tasks, "done"), "Schema.Boolean")
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("fragments used from another file are imported from its .graphql.ts", () =>
    Effect.gen(function*() {
      const { tasks } = yield* generate
      const match = /^import \{ (.+) \} from "\.\/fragments\.graphql\.ts"$/m.exec(tasks)
      assert(match !== null, "expected an import from ./fragments.graphql.ts")
      assert.sameMembers(match[1]!.split(", "), ["TaskCore", "TaskSchedule"])
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("documents are compact and append every fragment they use in order of first use", () =>
    Effect.gen(function*() {
      const { tasks } = yield* generate
      assert.strictEqual(
        documentOf(tasks, "OneTask"),
        "query OneTask($taskId:ID!){one:task(id:$taskId){...TaskCore}}fragment TaskCore on Task{id title}"
      )
      assert.strictEqual(
        documentOf(tasks, "Scheduled"),
        "query Scheduled{scheduled:tasks{...TaskSchedule estimate}}fragment TaskSchedule on Task{due...TaskCore}fragment TaskCore on Task{id title}"
      )
      assert.strictEqual(
        documentOf(tasks, "Both"),
        "query Both($taskId:ID!){core:task(id:$taskId){...TaskCore}later:tasks{...TaskSchedule estimate}}fragment TaskCore on Task{id title}fragment TaskSchedule on Task{due...TaskCore}"
      )
    }).pipe(Effect.provide(NodeServices.layer)))
})

describe("Generator GitHub documents", () => {
  it.effect("generates the fragments, issues and shared files with no diagnostics", () =>
    Effect.gen(function*() {
      const generated = yield* generateGitHub
      assertNoErrors(generated)
      assert.deepStrictEqual(warnings(generated), [])
      assert.deepStrictEqual(generated.paths, [
        "documents/fragments.graphql.ts",
        "documents/issues.graphql.ts",
        "documents/shared.graphql.ts"
      ])
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("issues.graphql exports RepoIssues, AddComment and IssuesGroup", () =>
    Effect.gen(function*() {
      const generated = yield* generateGitHub
      const issues = generated.file("documents/issues.graphql.ts")
      const lines = fileLines(issues)
      assert.include(lines, `export const RepoIssues = GraphQL.query("RepoIssues", {`)
      assert.include(lines, `export const AddComment = GraphQL.mutation("AddComment", {`)
      assert.include(lines, "export const IssuesGroup = GraphQLGroup.make(RepoIssues, AddComment)")
      assert.match(issues, /^import \{ IssueSummary \} from "\.\/fragments\.graphql\.ts"$/m)
      assert.match(issues, /^import \* as Shared from "\.\/shared\.graphql\.ts"$/m)
      assert.include(lines.map((line) => line.replace(/,$/, "")), "...IssueSummary.fields")
      assert.strictEqual(
        documentOf(issues, "RepoIssues"),
        "query RepoIssues($owner:String!,$name:String!,$states:[IssueState!],$first:Int=20,$orderBy:IssueOrder,$filterBy:IssueFilters){repository(owner:$owner,name:$name){id nameWithOwner issues(first:$first,states:$states,orderBy:$orderBy,filterBy:$filterBy){totalCount pageInfo{hasNextPage endCursor}nodes{...IssueSummary isPinned}}}}fragment IssueSummary on Issue{number title state stateReason createdAt url}"
      )
      assert.strictEqual(
        documentOf(issues, "AddComment"),
        "mutation AddComment($input:AddCommentInput!){addComment(input:$input){commentEdge{node{id url createdAt}}}}"
      )
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("fragments.graphql exports IssueSummary as an Opaque class and no group", () =>
    Effect.gen(function*() {
      const generated = yield* generateGitHub
      const fragmentsFile = generated.file("documents/fragments.graphql.ts")
      assert.match(
        declaration(fragmentsFile, "IssueSummary"),
        /^export class IssueSummary extends Schema\.Opaque<IssueSummary>\(\)\(/
      )
      assert.isFalse(fileLines(fragmentsFile).some((line) => groupDeclaration.test(line)))
    }).pipe(Effect.provide(NodeServices.layer)))

  it.effect("the shared module re-exports the mapped scalars from the fixture's scalars.ts", () =>
    Effect.gen(function*() {
      const generated = yield* generateGitHub
      const shared = generated.file("documents/shared.graphql.ts")
      assert.match(shared, /^import \* as \w+ from "\.\/scalars\.ts"$/m)
      assert.match(declaration(shared, "DateTime"), /^export const DateTime = \w+\.DateTime$/)
      assert.match(declaration(shared, "URI"), /^export const URI = \w+\.URI$/)
      for (const name of ["IssueState", "IssueStateReason", "IssueOrder", "IssueFilters", "AddCommentInput"]) {
        assert.isTrue(declares(shared, name), `expected ${name} in the shared module`)
      }
    }).pipe(Effect.provide(NodeServices.layer)))
})
