/**
 * The `graphqlgen` command (EFF-1834 points 1 to 13): config loading, exit
 * codes, all-or-nothing writes, stale-output cleanup and `--check`.
 *
 * Each test seeds a scratch project under `test/.tmp` (inside the package, so
 * a config file can import `@effect/graphql-generator/Config`) and runs the
 * command in process with `--config`. One test spawns `bin.ts` with no flags
 * so the config's `import()` runs under the real Node version.
 */
import * as Generator from "@effect/graphql-generator/Generator"
import * as NodeServices from "@effect/platform-node/NodeServices"
import { assert, describe, it } from "@effect/vitest"
import * as Cause from "effect/Cause"
import { CliOutput } from "effect/cli"
import * as Effect from "effect/Effect"
import * as Exit from "effect/Exit"
import * as FileSystem from "effect/FileSystem"
import * as Layer from "effect/Layer"
import * as Option from "effect/Option"
import * as Path from "effect/Path"
import { ChildProcess, ChildProcessSpawner } from "effect/process"
import * as Runtime from "effect/Runtime"
import * as Stdio from "effect/Stdio"
import * as Stream from "effect/Stream"
import { TestConsole } from "effect/testing"
import { fileURLToPath } from "node:url"

const schemaSdl = `scalar Url

type User {
  id: ID!
  name: String!
  avatar: Url
}

type Query {
  viewer: User!
}
`

const config = {
  schema: "./schema.graphql",
  documents: ["src/**/*.graphql"]
}

const configSource = (value: unknown): string =>
  `import { defineConfig } from "@effect/graphql-generator/Config"\n\nexport default defineConfig(${
    JSON.stringify(value, null, 2)
  })\n`

const header = (sourceName: string): string =>
  `// Generated by @effect/graphql-generator from ${sourceName}. Do not edit.\n`

const tmpRoot = fileURLToPath(new URL("./.tmp", import.meta.url))
const binPath = fileURLToPath(new URL("../src/bin.ts", import.meta.url))

/** Writes `files` (relative path to contents) to a fresh scratch directory, removed with the scope. */
const project = Effect.fnUntraced(function*(files: Readonly<Record<string, string>>) {
  const fs = yield* FileSystem.FileSystem
  const path = yield* Path.Path
  yield* fs.makeDirectory(tmpRoot, { recursive: true })
  const dir = yield* fs.makeTempDirectoryScoped({ directory: tmpRoot, prefix: "cli-" })
  yield* write(dir, files)
  return {
    dir,
    configPath: path.join(dir, "graphql.config.ts"),
    file: (relative: string) => path.join(dir, relative)
  }
})

const write = Effect.fnUntraced(function*(dir: string, files: Readonly<Record<string, string>>) {
  const fs = yield* FileSystem.FileSystem
  const path = yield* Path.Path
  for (const [relative, body] of Object.entries(files)) {
    const file = path.join(dir, relative)
    yield* fs.makeDirectory(path.dirname(file), { recursive: true })
    yield* fs.writeFileString(file, body)
  }
})

const baseProject = (documents: Readonly<Record<string, string>>, value: unknown = config) =>
  project({ "graphql.config.ts": configSource(value), "schema.graphql": schemaSdl, ...documents })

type CliMainModule = {
  readonly run: Effect.Effect<void, unknown>
}

const runCli = Effect.fnUntraced(function*(args: ReadonlyArray<string>) {
  const module = (yield* Effect.promise(
    () => import(new URL("../src/main.ts", import.meta.url).href)
  )) as CliMainModule

  return yield* Effect.gen(function*() {
    const exit = yield* Effect.exit(module.run)
    const stdout = (yield* TestConsole.logLines).map(String).join("\n")
    const stderr = (yield* TestConsole.errorLines).map(String).join("\n")
    return { exit, exitCode: exitCode(exit), stdout, stderr, output: `${stdout}\n${stderr}` } as const
  }).pipe(
    Effect.provide(Layer.mergeAll(
      TestConsole.layer,
      CliOutput.layer(CliOutput.defaultFormatter({ colors: false })),
      NodeServices.layer,
      Stdio.layerTest({ args: Effect.succeed(args) })
    ))
  )
})

/** The process exit code `NodeRuntime.runMain` would use for `exit`. */
const exitCode = (exit: Exit.Exit<void, unknown>): number =>
  Exit.isSuccess(exit) ? 0 : Runtime.getErrorExitCode(Cause.squash(exit.cause))

const exists = Effect.fnUntraced(function*(file: string) {
  const fs = yield* FileSystem.FileSystem
  return yield* fs.exists(file)
})

const read = Effect.fnUntraced(function*(file: string) {
  const fs = yield* FileSystem.FileSystem
  return yield* fs.readFileString(file)
})

/** Backdates `files` so a later write shows up as a changed mtime. */
const backdate = Effect.fnUntraced(function*(files: ReadonlyArray<string>) {
  const fs = yield* FileSystem.FileSystem
  for (const file of files) yield* fs.utimes(file, 0, 0)
})

const mtime = Effect.fnUntraced(function*(file: string) {
  const fs = yield* FileSystem.FileSystem
  const info = yield* fs.stat(file)
  return Option.getOrThrow(info.mtime).getTime()
})

describe("graphqlgen CLI", () => {
  it.effect("a clean run writes the generated files and exits 0; a second run writes nothing", () =>
    Effect.gen(function*() {
      const p = yield* baseProject({ "src/a.graphql": "query A {\n  viewer {\n    id\n    name\n  }\n}\n" })
      const expected = yield* Generator.generate(config, { cwd: p.dir })

      const first = yield* runCli(["--config", p.configPath])
      assert.strictEqual(first.exitCode, 0, first.output)
      assert.strictEqual(first.stderr, "")
      assert.isTrue(expected.files.length > 0)
      for (const file of expected.files) {
        assert.strictEqual(yield* read(file.path), file.contents, file.path)
      }

      const outputs = expected.files.map((file) => file.path)
      yield* backdate(outputs)
      const second = yield* runCli(["--config", p.configPath])
      assert.strictEqual(second.exitCode, 0, second.output)
      for (const file of outputs) {
        assert.strictEqual(yield* mtime(file), 0, `${file} was rewritten`)
      }
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("warnings print to stderr and the run still writes and exits 0", () =>
    Effect.gen(function*() {
      const p = yield* baseProject({ "src/a.graphql": "query A {\n  viewer {\n    avatar\n  }\n}\n" })

      const result = yield* runCli(["--config", p.configPath])
      assert.strictEqual(result.exitCode, 0, result.output)
      assert.include(result.stderr, "warning:")
      assert.include(result.stderr, "Url")
      assert.isTrue(yield* exists(p.file("src/a.graphql.ts")))
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("a validation error prints file:line:col with a code frame, writes nothing and exits 1", () =>
    Effect.gen(function*() {
      const p = yield* baseProject({
        "src/a.graphql": "query A {\n  viewer {\n    id\n  }\n}\n",
        "src/b.graphql": "query B {\n  viewer {\n    nope\n  }\n}\n"
      })

      const result = yield* runCli(["--config", p.configPath])
      assert.strictEqual(result.exitCode, 1, result.output)
      assert.include(result.stderr, `src/b.graphql:3:5: error: Cannot query field "nope" on type "User".`)
      assert.include(result.stderr, "3 |     nope")
      assert.isFalse(yield* exists(p.file("src/a.graphql.ts")))
      assert.isFalse(yield* exists(p.file("src/b.graphql.ts")))
      assert.isFalse(yield* exists(p.file("schema.graphql.ts")))
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("a config that fails to decode exits 2 naming the issue path", () =>
    Effect.gen(function*() {
      const p = yield* baseProject(
        { "src/a.graphql": "query A {\n  viewer {\n    id\n  }\n}\n" },
        { schema: "./schema.graphql", documents: "src/**/*.graphql" }
      )

      const result = yield* runCli(["--config", p.configPath])
      assert.strictEqual(result.exitCode, 2, result.output)
      assert.include(result.stderr, "documents")
      assert.isFalse(yield* exists(p.file("src/a.graphql.ts")))
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("a missing config exits 2", () =>
    Effect.gen(function*() {
      const p = yield* project({})

      const result = yield* runCli(["--config", p.file("graphql.config.ts")])
      assert.strictEqual(result.exitCode, 2, result.output)
      assert.include(result.stderr, "graphql.config.ts")
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("--check lists every create, change and delete, writes nothing and exits 1", () =>
    Effect.gen(function*() {
      const p = yield* baseProject({
        "src/changed.graphql": "query Changed {\n  viewer {\n    id\n  }\n}\n",
        "src/removed.graphql": "query Removed {\n  viewer {\n    id\n  }\n}\n"
      })
      const fs = yield* FileSystem.FileSystem
      const clean = yield* runCli(["--config", p.configPath])
      assert.strictEqual(clean.exitCode, 0, clean.output)

      const upToDate = yield* runCli(["--config", p.configPath, "--check"])
      assert.strictEqual(upToDate.exitCode, 0, upToDate.output)

      const changedBefore = yield* read(p.file("src/changed.graphql.ts"))
      yield* write(p.dir, {
        "src/changed.graphql": "query Changed {\n  viewer {\n    name\n  }\n}\n",
        "src/created.graphql": "query Created {\n  viewer {\n    id\n  }\n}\n"
      })
      yield* fs.remove(p.file("src/removed.graphql"))

      const result = yield* runCli(["--config", p.configPath, "--check"])
      assert.strictEqual(result.exitCode, 1, result.output)
      assert.include(result.output, "src/created.graphql.ts")
      assert.include(result.output, "src/changed.graphql.ts")
      assert.include(result.output, "src/removed.graphql.ts")
      assert.isFalse(yield* exists(p.file("src/created.graphql.ts")))
      assert.strictEqual(yield* read(p.file("src/changed.graphql.ts")), changedBefore)
      assert.isTrue(yield* exists(p.file("src/removed.graphql.ts")))
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("stale cleanup deletes a headered orphan and keeps unheadered files and the shared module", () =>
    Effect.gen(function*() {
      const handwritten = "export const handwritten = true\n"
      const p = yield* baseProject(
        {
          "src/a.graphql": "query A {\n  viewer {\n    id\n  }\n}\n",
          "src/orphan.graphql.ts": `${header("orphan.graphql")}export const Orphan = 1\n`,
          "src/handwritten.graphql.ts": handwritten
        },
        { ...config, shared: "./src/shared.graphql.ts" }
      )

      const first = yield* runCli(["--config", p.configPath])
      assert.strictEqual(first.exitCode, 0, first.output)
      assert.isFalse(yield* exists(p.file("src/orphan.graphql.ts")))
      assert.strictEqual(yield* read(p.file("src/handwritten.graphql.ts")), handwritten)
      assert.isTrue(yield* exists(p.file("src/a.graphql.ts")))
      assert.isTrue(yield* exists(p.file("src/shared.graphql.ts")))

      const second = yield* runCli(["--config", p.configPath])
      assert.strictEqual(second.exitCode, 0, second.output)
      assert.isTrue(yield* exists(p.file("src/shared.graphql.ts")))
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("documents skip the schema file, node_modules and dot-directories without a diagnostic", () =>
    Effect.gen(function*() {
      const p = yield* baseProject(
        {
          "src/a.graphql": "query A {\n  viewer {\n    id\n  }\n}\n",
          "node_modules/pkg/bad.graphql": "query {",
          ".cache/bad.graphql": "query {"
        },
        { schema: "./schema.graphql", documents: ["**/*.graphql"] }
      )

      const result = yield* runCli(["--config", p.configPath])
      assert.strictEqual(result.exitCode, 0, result.output)
      assert.strictEqual(result.stderr, "")
      assert.isTrue(yield* exists(p.file("src/a.graphql.ts")))
      assert.isTrue(yield* exists(p.file("schema.graphql.ts")))
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("--watch and --check are mutually exclusive", () =>
    Effect.gen(function*() {
      const p = yield* baseProject({ "src/a.graphql": "query A {\n  viewer {\n    id\n  }\n}\n" })

      const result = yield* runCli(["--config", p.configPath, "--watch", "--check"])
      assert.isTrue(Exit.isFailure(result.exit))
      assert.notStrictEqual(result.exitCode, 0)
      assert.isFalse(yield* exists(p.file("src/a.graphql.ts")))
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))

  it.effect("bin.ts loads graphql.config.ts from the working directory under Node", () =>
    Effect.gen(function*() {
      const p = yield* baseProject({ "src/a.graphql": "query A {\n  viewer {\n    id\n  }\n}\n" })

      const handle = yield* ChildProcess.make("node", [binPath], { cwd: p.dir })
      const result = yield* Effect.all({
        exitCode: handle.exitCode,
        stdout: Stream.mkString(Stream.decodeText(handle.stdout)),
        stderr: Stream.mkString(Stream.decodeText(handle.stderr))
      }, { concurrency: "unbounded" })

      assert.strictEqual(result.exitCode, ChildProcessSpawner.ExitCode(0), result.stderr)
      assert.include(yield* read(p.file("src/a.graphql.ts")), header("a.graphql"))
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)))
})
