/**
 * Acceptance check for both schema readers (EFF-1829 point 3): the GitHub
 * introspection JSON and the SDL printed from it produce equal models.
 *
 * `schema.json` and `schema.graphql` describe the same snapshot (see
 * `test/fixtures/github/README.md`). `schema.docs.graphql` is a different,
 * newer snapshot and is only read on its own.
 */
import type * as Model from "@effect/graphql-generator/internal/SchemaModel"
import { assert, describe, it } from "@effect/vitest"
import {
  assertModelsEqual,
  assertType,
  enumType,
  enumValue,
  field,
  fixture,
  inputObjectType,
  inputValue,
  interfaceType,
  named,
  nonNull,
  readIntrospection,
  readSdl,
  scalarType,
  unionType
} from "./utils/model.ts"

let cache: { readonly json: string; readonly fromJson: Model.Schema; readonly fromSdl: Model.Schema } | undefined
const github = () => {
  if (cache === undefined) {
    const json = fixture("github/schema.json")
    cache = {
      json,
      fromJson: readIntrospection(json, "github/schema.json"),
      fromSdl: readSdl(fixture("github/schema.graphql"), "github/schema.graphql")
    }
  }
  return cache
}

const topicSuggestionDeclined = "Suggested topics are no longer supported Removal on 2024-04-01 UTC."

describe("schema readers: GitHub", () => {
  it("the SDL and the introspection JSON produce equal models", () => {
    const { fromJson, fromSdl } = github()
    assertModelsEqual(fromSdl, fromJson)
  })

  it("the model has every non-meta type and the custom directive", () => {
    const { fromJson } = github()
    assert.strictEqual(fromJson.queryType, "Query")
    assert.strictEqual(fromJson.mutationType, "Mutation")
    assert.isUndefined(fromJson.subscriptionType)
    // 1606 introspection types less the eight `__` meta types.
    assert.strictEqual(fromJson.types.size, 1598)
    assert.isFalse(Array.from(fromJson.types.keys()).some((name) => name.startsWith("__")))
    assert.deepStrictEqual(Array.from(fromJson.directives.keys()), ["requiredCapabilities"])
  })

  it("spot checks: deprecated enum values, a parsed default, union and interface members", () => {
    const { fromJson, fromSdl } = github()
    const expected: ReadonlyArray<Model.NamedType> = [
      enumType("TopicSuggestionDeclineReason", [
        enumValue("NOT_RELEVANT", {
          description: "The suggested topic is not relevant to the repository.",
          deprecationReason: topicSuggestionDeclined
        }),
        enumValue("TOO_SPECIFIC", {
          description: "The suggested topic is too specific for the repository (e.g. #ruby-on-rails-version-4-2-1).",
          deprecationReason: topicSuggestionDeclined
        }),
        enumValue("PERSONAL_PREFERENCE", {
          description: "The viewer does not like the suggested topic.",
          deprecationReason: topicSuggestionDeclined
        }),
        enumValue("TOO_GENERAL", {
          description: "The suggested topic is too general for the repository.",
          deprecationReason: topicSuggestionDeclined
        })
      ], { description: "Reason that the suggested topic is declined." }),
      inputObjectType("CloseDiscussionInput", [
        inputValue("clientMutationId", named("String"), {
          description: "A unique identifier for the client performing the mutation."
        }),
        inputValue("discussionId", nonNull(named("ID")), { description: "ID of the discussion to be closed." }),
        inputValue("reason", named("DiscussionCloseReason"), {
          description: "The reason why the discussion is being closed.",
          defaultValue: { _tag: "EnumValue", value: "RESOLVED" }
        })
      ], { description: "Autogenerated input type of CloseDiscussion" }),
      unionType("DeploymentReviewer", ["Team", "User"], { description: "Users and teams." }),
      interfaceType("Lockable", [
        field("activeLockReason", named("LockReason"), { description: "Reason that the conversation was locked." }),
        field("locked", nonNull(named("Boolean")), { description: "`true` if the object is locked" })
      ], { description: "An object that can be locked.", possibleTypes: ["Discussion", "Issue", "PullRequest"] }),
      scalarType("String")
    ]
    for (const model of [fromJson, fromSdl]) {
      for (const type of expected) assertType(model, type)
    }
  })

  it("accepts the { data: { __schema } } response shape", () => {
    const { fromJson, json } = github()
    const wrapped = readIntrospection(`{"data":${json}}`, "github/response.json")
    assertModelsEqual(wrapped, fromJson)
  })

  it("reads the github/docs SDL, dropping its applied custom directives", () => {
    const model = readSdl(fixture("github/schema.docs.graphql"), "github/schema.docs.graphql")
    // 1824 type definitions (see GitHubFixture.test.ts) plus the five built-in scalars.
    assert.strictEqual(model.types.size, 1829)
    assert.deepStrictEqual(Array.from(model.directives.keys()).sort(), ["docsCategory", "possibleTypes", "preview"])
    assert.strictEqual(model.queryType, "Query")
    assert.strictEqual(model.mutationType, "Mutation")
  })
})
