name: Setup
description: Perform standard setup and install dependencies using pnpm.
inputs:
  cachixAuthToken:
    description: The cachix auth token
    required: true

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "::set-output name=pnpm_cache_dir::$(nix develop --command -- pnpm store path)"
    - uses: actions/cache@v3
      name: Cache pnpm
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: nix develop --command -- pnpm install --ignore-scripts
