// eslint-disable-next-line
module.exports = {
  rootDir: "./",
  clearMocks: true,
  collectCoverage: false,
  coverageDirectory: "coverage",
  collectCoverageFrom: [
    "packages/**/src/**/*.ts",
    "packages_be/**/src/**/*.ts",
    "packages_fe/**/src/**/*.ts",
    "packages_http/**/src/**/*.ts",
    "packages_inc/**/src/**/*.ts",
    "packages_sys/**/src/**/*.ts"
  ],
  setupFiles: ["./jest-setup.ts"],
  modulePathIgnorePatterns: ["dtslint", "build"],
  verbose: false,
  moduleNameMapper: {
    "@matechs/core/(.*)$": "<rootDir>/packages/core/build/$1",
    "@matechs/core$": "<rootDir>/packages/core/build",
    "@matechs/contrib/(.*)$": "<rootDir>/packages/contrib/build",
    "@matechs/contrib$": "<rootDir>/packages/contrib/build/$1",
    "@matechs/test/(.*)$": "<rootDir>/packages/test/build/$1",
    "@matechs/test$": "<rootDir>/packages/test/build",
    "@matechs/test-jest/(.*)$": "<rootDir>/packages/test-jest/build/$1",
    "@matechs/test-jest$": "<rootDir>/packages/test-jest/build",
    "@matechs/aio/(.*)$": "<rootDir>/packages/aio/build/$1",
    "@matechs/aio$": "<rootDir>/packages/aio/build",
    "@matechs/graceful/(.*)$": "<rootDir>/packages_be/graceful/build/$1",
    "@matechs/graceful$": "<rootDir>/packages_be/graceful/build",
    "@matechs/orm/(.*)$": "<rootDir>/packages_be/orm/build/$1",
    "@matechs/orm$": "<rootDir>/packages_be/orm/build",
    "@matechs/tracing/(.*)$": "<rootDir>/packages_be/tracing/build/$1",
    "@matechs/tracing$": "<rootDir>/packages_be/tracing/build",
    "@matechs/uuid/(.*)$": "<rootDir>/packages_be/uuid/build/$1",
    "@matechs/uuid$": "<rootDir>/packages_be/uuid/build",
    "@matechs/zoo/(.*)$": "<rootDir>/packages_be/zoo/build/$1",
    "@matechs/zoo$": "<rootDir>/packages_be/zoo/build",
    "@matechs/browser/(.*)$": "<rootDir>/packages_fe/browser/build/$1",
    "@matechs/browser$": "<rootDir>/packages_fe/browser/build",
    "@matechs/rxjs/(.*)$": "<rootDir>/packages_fe/rxjs/build/$1",
    "@matechs/rxjs$": "<rootDir>/packages_fe/rxjs/build",
    "@matechs/epics/(.*)$": "<rootDir>/packages_fe/epics/build/$1",
    "@matechs/epics$": "<rootDir>/packages_fe/epics/build",
    "@matechs/console/(.*)$": "<rootDir>/packages_sys/console/build/$1",
    "@matechs/console$": "<rootDir>/packages_sys/console/build",
    "@matechs/logger/(.*)$": "<rootDir>/packages_sys/logger/build/$1",
    "@matechs/logger$": "<rootDir>/packages_sys/logger/build",
    "@matechs/logger-pino/(.*)$": "<rootDir>/packages_sys/logger-pino/build/$1",
    "@matechs/logger-pino$": "<rootDir>/packages_sys/logger-pino/build",
    "@matechs/logger-winston/(.*)$": "<rootDir>/packages_sys/logger-winston/build/$1",
    "@matechs/logger-winston$": "<rootDir>/packages_sys/logger-winston/build",
    "@matechs/http-client/(.*)$": "<rootDir>/packages_http/http-client/build/$1",
    "@matechs/http-client$": "<rootDir>/packages_http/http-client/build",
    "@matechs/http-client-fetch/(.*)$":
      "<rootDir>/packages_http/http-client-fetch/build/$1",
    "@matechs/http-client-fetch$": "<rootDir>/packages_http/http-client-fetch/build",
    "@matechs/http-client-libcurl/(.*)$":
      "<rootDir>/packages_http/http-client-libcurl/build/$1",
    "@matechs/http-client-libcurl$":
      "<rootDir>/packages_http/http-client-libcurl/build",
    "@matechs/express/(.*)$": "<rootDir>/packages_http/express/build/$1",
    "@matechs/express$": "<rootDir>/packages_http/express/build",
    "@matechs/apollo/(.*)$": "<rootDir>/packages_http/apollo/build/$1",
    "@matechs/apollo$": "<rootDir>/packages_http/apollo/build",
    "@matechs/koa/(.*)$": "<rootDir>/packages_http/koa/build/$1",
    "@matechs/koa$": "<rootDir>/packages_http/koa/build",
    "@matechs/rpc-client/(.*)$": "<rootDir>/packages_http/rpc-client/build/$1",
    "@matechs/rpc-client$": "<rootDir>/packages_http/rpc-client/build",
    "@matechs/rpc/(.*)$": "<rootDir>/packages_http/rpc/build/$1",
    "@matechs/rpc$": "<rootDir>/packages_http/rpc/build",
    "@matechs/cqrs/(.*)$": "<rootDir>/packages_inc/cqrs/build/$1",
    "@matechs/cqrs$": "<rootDir>/packages_inc/cqrs/build",
    "@matechs/cqrs-es/(.*)$": "<rootDir>/packages_inc/cqrs-es/build/$1",
    "@matechs/cqrs-es$": "<rootDir>/packages_inc/cqrs-es/build",
    "@matechs/fancy/(.*)$": "<rootDir>/packages_inc/fancy/build/$1",
    "@matechs/fancy$": "<rootDir>/packages_inc/fancy/build",
    "@matechs/morphic-alg/(.*)$": "<rootDir>/packages/morphic-alg/build/$1",
    "@matechs/morphic-alg$": "<rootDir>/packages/morphic-alg/build",
    "@matechs/morphic/(.*)$": "<rootDir>/packages/morphic/build/$1",
    "@matechs/morphic$": "<rootDir>/packages/morphic/build"
  }
}
