packages:
  - ai-docs
  - scratchpad
  - scripts
  - packages/*
  - packages/ai/*
  - packages/atom/*
  - packages/platform/*
  - packages/sql/*
  - packages/tools/*
  - examples/*

allowBuilds:
  core-js: false
  cpu-features: false
  dprint: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
  sharp: false
  ssh2: false
  tree-sitter: false
  tree-sitter-javascript: false
  tree-sitter-typescript: false
  workerd: false

patchedDependencies:
  '@changesets/get-github-info@1.0.0-next.4': patches/@changesets__get-github-info@1.0.0-next.4.patch
  '@changesets/read@1.0.0-next.10': patches/@changesets__read@1.0.0-next.10.patch
