/*
 * Mapping data from iconv-lite 2472166ea5a4825ca091b9550713c403852a566b.
 * Generated by scripts/generate-character-encoding.ts; do not edit.
 *
 * Copyright (c) 2011 Alexander Shtuchkin
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
import big5hkscs from "./big5hkscsData.ts"
import cp936 from "./cp936Data.ts"
import cp949 from "./cp949Data.ts"
import cp950 from "./cp950Data.ts"
import eucjp from "./eucjpData.ts"
import gb18030 from "./gb18030Data.ts"
import gbk from "./gbkData.ts"
import shiftjis from "./shiftjisData.ts"
import type { Mapping } from "./types.ts"
export const definitions: Readonly<Record<string, Mapping>> = {
  shiftjis,
  eucjp,
  cp936,
  gbk,
  gb18030,
  cp949,
  cp950,
  big5hkscs
}
export const aliases: Readonly<Record<string, string>> = {
  "932": "shiftjis",
  "936": "cp936",
  "949": "cp949",
  "950": "cp950",
  "csshiftjis": "shiftjis",
  "mskanji": "shiftjis",
  "sjis": "shiftjis",
  "windows31j": "shiftjis",
  "ms31j": "shiftjis",
  "xsjis": "shiftjis",
  "windows932": "shiftjis",
  "ms932": "shiftjis",
  "cp932": "shiftjis",
  "gb2312": "cp936",
  "gb231280": "cp936",
  "gb23121980": "cp936",
  "csgb2312": "cp936",
  "csiso58gb231280": "cp936",
  "euccn": "cp936",
  "windows936": "cp936",
  "ms936": "cp936",
  "xgbk": "gbk",
  "isoir58": "gbk",
  "chinese": "gb18030",
  "windows949": "cp949",
  "ms949": "cp949",
  "cseuckr": "cp949",
  "csksc56011987": "cp949",
  "euckr": "cp949",
  "isoir149": "cp949",
  "korean": "cp949",
  "ksc56011987": "cp949",
  "ksc56011989": "cp949",
  "ksc5601": "cp949",
  "windows950": "cp950",
  "ms950": "cp950",
  "big5": "big5hkscs",
  "cnbig5": "big5hkscs",
  "csbig5": "big5hkscs",
  "xxbig5": "big5hkscs"
}
