// codegen:start {preset: barrel, include: ./TDequeue/*.ts, prefix: "@effect/core/stm/THub/operations"}
export * from "@effect/core/stm/THub/operations/TDequeue/awaitShutdown"
export * from "@effect/core/stm/THub/operations/TDequeue/capacity"
export * from "@effect/core/stm/THub/operations/TDequeue/isEmpty"
export * from "@effect/core/stm/THub/operations/TDequeue/isFull"
export * from "@effect/core/stm/THub/operations/TDequeue/isShutdown"
export * from "@effect/core/stm/THub/operations/TDequeue/make"
export * from "@effect/core/stm/THub/operations/TDequeue/peek"
export * from "@effect/core/stm/THub/operations/TDequeue/peekOption"
export * from "@effect/core/stm/THub/operations/TDequeue/poll"
export * from "@effect/core/stm/THub/operations/TDequeue/seek"
export * from "@effect/core/stm/THub/operations/TDequeue/shutdown"
export * from "@effect/core/stm/THub/operations/TDequeue/size"
export * from "@effect/core/stm/THub/operations/TDequeue/take"
export * from "@effect/core/stm/THub/operations/TDequeue/takeAll"
export * from "@effect/core/stm/THub/operations/TDequeue/takeBetween"
export * from "@effect/core/stm/THub/operations/TDequeue/takeN"
export * from "@effect/core/stm/THub/operations/TDequeue/takeRemainder"
export * from "@effect/core/stm/THub/operations/TDequeue/takeUpTo"
// codegen:end
