/**
 * Opt-in registry of every encoding. Use individual codec modules for selective bundles.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import { makeRegistry } from "../CharacterEncoding.ts"
import type { Registry } from "../CharacterEncoding.ts"
import * as Armscii8 from "./Armscii8.ts"
import * as Ascii from "./Ascii.ts"
import * as Big5Hkscs from "./Big5Hkscs.ts"
import * as Cp1046 from "./Cp1046.ts"
import * as Cp1124 from "./Cp1124.ts"
import * as Cp1125 from "./Cp1125.ts"
import * as Cp1129 from "./Cp1129.ts"
import * as Cp1133 from "./Cp1133.ts"
import * as Cp1161 from "./Cp1161.ts"
import * as Cp1162 from "./Cp1162.ts"
import * as Cp1163 from "./Cp1163.ts"
import * as Cp437 from "./Cp437.ts"
import * as Cp720 from "./Cp720.ts"
import * as Cp737 from "./Cp737.ts"
import * as Cp775 from "./Cp775.ts"
import * as Cp808 from "./Cp808.ts"
import * as Cp850 from "./Cp850.ts"
import * as Cp852 from "./Cp852.ts"
import * as Cp855 from "./Cp855.ts"
import * as Cp856 from "./Cp856.ts"
import * as Cp857 from "./Cp857.ts"
import * as Cp858 from "./Cp858.ts"
import * as Cp860 from "./Cp860.ts"
import * as Cp861 from "./Cp861.ts"
import * as Cp862 from "./Cp862.ts"
import * as Cp863 from "./Cp863.ts"
import * as Cp864 from "./Cp864.ts"
import * as Cp865 from "./Cp865.ts"
import * as Cp866 from "./Cp866.ts"
import * as Cp869 from "./Cp869.ts"
import * as Cp922 from "./Cp922.ts"
import * as Cp936 from "./Cp936.ts"
import * as Cp949 from "./Cp949.ts"
import * as Cp950 from "./Cp950.ts"
import * as EucJp from "./EucJp.ts"
import * as Gb18030 from "./Gb18030.ts"
import * as Gbk from "./Gbk.ts"
import * as Georgianacademy from "./Georgianacademy.ts"
import * as Georgianps from "./Georgianps.ts"
import * as Hproman8 from "./Hproman8.ts"
import * as Iso646cn from "./Iso646cn.ts"
import * as Iso646jp from "./Iso646jp.ts"
import * as Iso88591 from "./Iso88591.ts"
import * as Iso885910 from "./Iso885910.ts"
import * as Iso885911 from "./Iso885911.ts"
import * as Iso885913 from "./Iso885913.ts"
import * as Iso885914 from "./Iso885914.ts"
import * as Iso885915 from "./Iso885915.ts"
import * as Iso885916 from "./Iso885916.ts"
import * as Iso88592 from "./Iso88592.ts"
import * as Iso88593 from "./Iso88593.ts"
import * as Iso88594 from "./Iso88594.ts"
import * as Iso88595 from "./Iso88595.ts"
import * as Iso88596 from "./Iso88596.ts"
import * as Iso88597 from "./Iso88597.ts"
import * as Iso88598 from "./Iso88598.ts"
import * as Iso88599 from "./Iso88599.ts"
import * as Koi8r from "./Koi8r.ts"
import * as Koi8ru from "./Koi8ru.ts"
import * as Koi8t from "./Koi8t.ts"
import * as Koi8u from "./Koi8u.ts"
import * as Maccenteuro from "./Maccenteuro.ts"
import * as Maccroatian from "./Maccroatian.ts"
import * as Maccyrillic from "./Maccyrillic.ts"
import * as Macgreek from "./Macgreek.ts"
import * as Maciceland from "./Maciceland.ts"
import * as Macintosh from "./Macintosh.ts"
import * as Macroman from "./Macroman.ts"
import * as Macromania from "./Macromania.ts"
import * as Macthai from "./Macthai.ts"
import * as Macturkish from "./Macturkish.ts"
import * as Macukraine from "./Macukraine.ts"
import * as Mik from "./Mik.ts"
import * as Pt154 from "./Pt154.ts"
import * as Rk1048 from "./Rk1048.ts"
import * as ShiftJis from "./ShiftJis.ts"
import * as Tcvn from "./Tcvn.ts"
import * as Tis620 from "./Tis620.ts"
import * as Utf16BE from "./Utf16BE.ts"
import * as Utf16LE from "./Utf16LE.ts"
import * as Utf32BE from "./Utf32BE.ts"
import * as Utf32LE from "./Utf32LE.ts"
import * as Utf8 from "./Utf8.ts"
import * as Viscii from "./Viscii.ts"
import * as Windows1250 from "./Windows1250.ts"
import * as Windows1251 from "./Windows1251.ts"
import * as Windows1252 from "./Windows1252.ts"
import * as Windows1253 from "./Windows1253.ts"
import * as Windows1254 from "./Windows1254.ts"
import * as Windows1255 from "./Windows1255.ts"
import * as Windows1256 from "./Windows1256.ts"
import * as Windows1257 from "./Windows1257.ts"
import * as Windows1258 from "./Windows1258.ts"
import * as Windows874 from "./Windows874.ts"
/**
 * All built-in encodings and aliases. Resolution does not construct lookup tables.
 *
 * @category encodings
 * @since 4.0.0
 */
export const registry: Registry = /* @__PURE__ */ makeRegistry([
  Armscii8.encoding,
  Ascii.encoding,
  Big5Hkscs.encoding,
  Cp1046.encoding,
  Cp1124.encoding,
  Cp1125.encoding,
  Cp1129.encoding,
  Cp1133.encoding,
  Cp1161.encoding,
  Cp1162.encoding,
  Cp1163.encoding,
  Cp437.encoding,
  Cp720.encoding,
  Cp737.encoding,
  Cp775.encoding,
  Cp808.encoding,
  Cp850.encoding,
  Cp852.encoding,
  Cp855.encoding,
  Cp856.encoding,
  Cp857.encoding,
  Cp858.encoding,
  Cp860.encoding,
  Cp861.encoding,
  Cp862.encoding,
  Cp863.encoding,
  Cp864.encoding,
  Cp865.encoding,
  Cp866.encoding,
  Cp869.encoding,
  Cp922.encoding,
  Cp936.encoding,
  Cp949.encoding,
  Cp950.encoding,
  EucJp.encoding,
  Gb18030.encoding,
  Gbk.encoding,
  Georgianacademy.encoding,
  Georgianps.encoding,
  Hproman8.encoding,
  Iso646cn.encoding,
  Iso646jp.encoding,
  Iso88591.encoding,
  Iso885910.encoding,
  Iso885911.encoding,
  Iso885913.encoding,
  Iso885914.encoding,
  Iso885915.encoding,
  Iso885916.encoding,
  Iso88592.encoding,
  Iso88593.encoding,
  Iso88594.encoding,
  Iso88595.encoding,
  Iso88596.encoding,
  Iso88597.encoding,
  Iso88598.encoding,
  Iso88599.encoding,
  Koi8r.encoding,
  Koi8ru.encoding,
  Koi8t.encoding,
  Koi8u.encoding,
  Maccenteuro.encoding,
  Maccroatian.encoding,
  Maccyrillic.encoding,
  Macgreek.encoding,
  Maciceland.encoding,
  Macintosh.encoding,
  Macroman.encoding,
  Macromania.encoding,
  Macthai.encoding,
  Macturkish.encoding,
  Macukraine.encoding,
  Mik.encoding,
  Pt154.encoding,
  Rk1048.encoding,
  ShiftJis.encoding,
  Tcvn.encoding,
  Tis620.encoding,
  Utf16BE.encoding,
  Utf16LE.encoding,
  Utf32BE.encoding,
  Utf32LE.encoding,
  Utf8.encoding,
  Viscii.encoding,
  Windows1250.encoding,
  Windows1251.encoding,
  Windows1252.encoding,
  Windows1253.encoding,
  Windows1254.encoding,
  Windows1255.encoding,
  Windows1256.encoding,
  Windows1257.encoding,
  Windows1258.encoding,
  Windows874.encoding
])
/**
 * All canonical codec descriptors.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encodings: Registry["encodings"] = registry.encodings
/**
 * Resolves a label with CharacterEncodingError in the Effect error channel.
 *
 * @category encodings
 * @since 4.0.0
 */
export const resolve: Registry["resolve"] = registry.resolve
/**
 * Resolves a label synchronously, throwing CharacterEncodingError when unknown.
 *
 * @category encodings
 * @since 4.0.0
 */
export const resolveUnsafe: Registry["resolveUnsafe"] = registry.resolveUnsafe
/**
 * Tests whether a label is supported by this registry.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encodingExists: Registry["encodingExists"] = registry.encodingExists
