/**
 * Explicit ascii codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import data from "../internal/characterEncoding/asciiData.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The ascii encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("ascii", [
  "ascii8bit",
  "usascii",
  "ansix34",
  "ansix341968",
  "ansix341986",
  "csascii",
  "cp367",
  "ibm367",
  "isoir6",
  "iso646us",
  "iso646irv",
  "us"
], () => new SingleByte(data))
