/**
 * Explicit big5hkscs codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import data from "../internal/characterEncoding/big5hkscsData.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import { MultiByte } from "../internal/characterEncoding/multiByte.ts"
/**
 * The big5hkscs encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "big5hkscs",
  ["big5", "cnbig5", "csbig5", "xxbig5"],
  () => new MultiByte(data)
)
