/**
 * Explicit cp858 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/cp858Data.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The cp858 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "cp858",
  ["858", "ibm858", "csibm858"],
  () => new SingleByte(data)
)
