/**
 * Explicit cp936 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/cp936Data.ts"
import { MultiByte } from "../internal/characterEncoding/multiByte.ts"
/**
 * The cp936 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("cp936", [
  "936",
  "gb2312",
  "gb231280",
  "gb23121980",
  "csgb2312",
  "csiso58gb231280",
  "euccn",
  "windows936",
  "ms936"
], () => new MultiByte(data))
