/**
 * Explicit gb18030 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/gb18030Data.ts"
import { MultiByte } from "../internal/characterEncoding/multiByte.ts"
/**
 * The gb18030 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("gb18030", ["chinese"], () => new MultiByte(data))
