/**
 * Explicit hproman8 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/hproman8Data.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The hproman8 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "hproman8",
  ["cshproman8", "r8", "roman8", "xroman8", "ibm1051"],
  () => new SingleByte(data)
)
