/**
 * Explicit iso885911 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/iso885911Data.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The iso885911 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "iso885911",
  ["28601", "thai", "thai8", "cp28601"],
  () => new SingleByte(data)
)
