/**
 * Explicit iso88592 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/iso88592Data.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The iso88592 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("iso88592", [
  "28592",
  "latin2",
  "csisolatin2",
  "l2",
  "isoir101",
  "cp28592"
], () => new SingleByte(data))
