/**
 * Explicit iso885916 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/iso885916Data.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The iso885916 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "iso885916",
  ["28606", "latin10", "l10", "isoir226", "cp28606"],
  () => new SingleByte(data)
)
