/**
 * Explicit iso88597 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/iso88597Data.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The iso88597 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("iso88597", [
  "28597",
  "csisolatingreek",
  "isoir126",
  "greek",
  "greek8",
  "ecma118",
  "elot928",
  "cp28597"
], () => new SingleByte(data))
