/**
 * Explicit iso88593 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/iso88593Data.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The iso88593 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("iso88593", [
  "28593",
  "latin3",
  "csisolatin3",
  "l3",
  "isoir109",
  "cp28593"
], () => new SingleByte(data))
