/**
 * Explicit koi8u codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/koi8uData.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The koi8u encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "koi8u",
  ["21866", "cp21866", "ibm1168"],
  () => new SingleByte(data)
)
