/**
 * MACUKRAINE character encoding with typed failures and Effect streams.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { CharacterEncodingError, Encoding, Options } from "../CharacterEncoding.ts"
import * as Effect from "../Effect.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/macukraineData.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
import { concat } from "../internal/characterEncoding/types.ts"
import * as Stream from "../Stream.ts"

/**
 * The macukraine codec descriptor, for use with the CharacterEncoding operators.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("macukraine", () => new SingleByte(data))

const attempt = <A>(operation: "encode" | "decode", f: () => A): A => {
  try {
    return f()
  } catch (cause) {
    throw {
      encoding: "macukraine",
      operation,
      message: String(cause),
      cause,
      _tag: "CharacterEncodingError"
    }
  }
}

/**
 * Encodes a complete string to macukraine bytes, throwing CharacterEncodingError on failure.
 *
 * @category encoding
 * @since 4.0.0
 */
export const encodeUnsafe = (text: string, options?: Options): Uint8Array => {
  const encoder = attempt("encode", () => encoding.makeEncoder(options ?? {}))
  return attempt("encode", () => concat(encoder.write(text), encoder.end()))
}

/**
 * Decodes complete macukraine bytes to a string, throwing CharacterEncodingError on failure.
 *
 * @category decoding
 * @since 4.0.0
 */
export const decodeUnsafe = (bytes: Uint8Array, options?: Options): string => {
  const decoder = attempt("decode", () => encoding.makeDecoder(options ?? {}))
  return attempt("decode", () => decoder.write(bytes) + decoder.end())
}

/**
 * Encodes a string to macukraine bytes with conversion errors in the Effect error channel.
 *
 * @category encoding
 * @since 4.0.0
 */
export const encode = (
  text: string,
  options?: Options
): Effect.Effect<Uint8Array, CharacterEncodingError> =>
  Effect.try({ try: () => encodeUnsafe(text, options), catch: (error) => error as CharacterEncodingError })

/**
 * Decodes macukraine bytes to a string with conversion errors in the Effect error channel.
 *
 * @category decoding
 * @since 4.0.0
 */
export const decode = (
  bytes: Uint8Array,
  options?: Options
): Effect.Effect<string, CharacterEncodingError> =>
  Effect.try({ try: () => decodeUnsafe(bytes, options), catch: (error) => error as CharacterEncodingError })

/**
 * Encodes a stream of strings to macukraine bytes incrementally, preserving codec state across chunks.
 *
 * @category streaming
 * @since 4.0.0
 */
export const encodeStream =
  (options?: Options) =>
  <E, R>(self: Stream.Stream<string, E, R>): Stream.Stream<Uint8Array, E | CharacterEncodingError, R> =>
    Stream.unwrap(Effect.map(
      Effect.try({
        try: () => attempt("encode", () => encoding.makeEncoder(options ?? {})),
        catch: (error) => error as CharacterEncodingError
      }),
      (encoder) =>
        Stream.concat(
          Stream.mapEffect(self, (text) =>
            Effect.try({
              try: () => encoder.write(text),
              catch: (error) => error as CharacterEncodingError
            })),
          Stream.fromEffect(Effect.try({
            try: () => encoder.end(),
            catch: (error) => error as CharacterEncodingError
          }))
        )
    ))

/**
 * Decodes a stream of macukraine bytes to strings incrementally, retaining partial sequences across chunks.
 *
 * @category streaming
 * @since 4.0.0
 */
export const decodeStream =
  (options?: Options) =>
  <E, R>(self: Stream.Stream<Uint8Array, E, R>): Stream.Stream<string, E | CharacterEncodingError, R> =>
    Stream.unwrap(Effect.map(
      Effect.try({
        try: () => attempt("decode", () => encoding.makeDecoder(options ?? {})),
        catch: (error) => error as CharacterEncodingError
      }),
      (decoder) =>
        Stream.concat(
          Stream.mapEffect(self, (bytes) =>
            Effect.try({
              try: () => decoder.write(bytes),
              catch: (error) => error as CharacterEncodingError
            })),
          Stream.fromEffect(Effect.try({
            try: () => decoder.end(),
            catch: (error) => error as CharacterEncodingError
          }))
        )
    ))
