/**
 * Explicit rk1048 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import data from "../internal/characterEncoding/rk1048Data.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
/**
 * The rk1048 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("rk1048", ["strk10482002"], () => new SingleByte(data))
