/**
 * Explicit shiftjis codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import { MultiByte } from "../internal/characterEncoding/multiByte.ts"
import data from "../internal/characterEncoding/shiftjisData.ts"
/**
 * The shiftjis encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make("shiftjis", [
  "932",
  "csshiftjis",
  "mskanji",
  "sjis",
  "windows31j",
  "ms31j",
  "xsjis",
  "windows932",
  "ms932",
  "cp932"
], () => new MultiByte(data))
