/**
 * Explicit utf16le codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import * as Unicode from "../internal/characterEncoding/unicode.ts"
/**
 * The utf16le encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "utf16le",
  ["ucs2", "ucs2le"],
  () => ({
    encoder: (options) => Unicode.encoder("utf16le", options),
    decoder: (options) => Unicode.decoder("utf16le", options)
  }),
  true
)
