/**
 * Explicit windows1257 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
import data from "../internal/characterEncoding/windows1257Data.ts"
/**
 * The windows1257 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "windows1257",
  ["1257", "winbaltrim", "win1257", "cp1257"],
  () => new SingleByte(data)
)
