/**
 * Explicit windows1252 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
import data from "../internal/characterEncoding/windows1252Data.ts"
/**
 * The windows1252 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "windows1252",
  ["1252", "msansi", "win1252", "cp1252"],
  () => new SingleByte(data)
)
