/**
 * Explicit windows1258 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
import data from "../internal/characterEncoding/windows1258Data.ts"
/**
 * The windows1258 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "windows1258",
  ["1258", "win1258", "cp1258"],
  () => new SingleByte(data)
)
