/**
 * Explicit windows1253 codec. Does not import other encoding tables.
 *
 * @since 4.0.0
 */
// Generated by scripts/generate-character-encoding.ts; do not edit.
import type { Encoding } from "../CharacterEncoding.ts"
import { make } from "../internal/characterEncoding/codec.ts"
import { SingleByte } from "../internal/characterEncoding/singleByte.ts"
import data from "../internal/characterEncoding/windows1253Data.ts"
/**
 * The windows1253 encoding. Lookup tables are constructed lazily on first conversion.
 *
 * @category encodings
 * @since 4.0.0
 */
export const encoding: Encoding = /* @__PURE__ */ make(
  "windows1253",
  ["1253", "msgreek", "win1253", "cp1253"],
  () => new SingleByte(data)
)
