// codegen:start {preset: barrel, include: ./operations/*.ts, prefix: "@effect/core/io/RuntimeFlags/patch"}
export * from "@effect/core/io/RuntimeFlags/patch/operations/active"
export * from "@effect/core/io/RuntimeFlags/patch/operations/andThen"
export * from "@effect/core/io/RuntimeFlags/patch/operations/both"
export * from "@effect/core/io/RuntimeFlags/patch/operations/disabledSet"
export * from "@effect/core/io/RuntimeFlags/patch/operations/either"
export * from "@effect/core/io/RuntimeFlags/patch/operations/enabled"
export * from "@effect/core/io/RuntimeFlags/patch/operations/enabledSet"
export * from "@effect/core/io/RuntimeFlags/patch/operations/exclude"
export * from "@effect/core/io/RuntimeFlags/patch/operations/includes"
export * from "@effect/core/io/RuntimeFlags/patch/operations/inverse"
export * from "@effect/core/io/RuntimeFlags/patch/operations/isActive"
export * from "@effect/core/io/RuntimeFlags/patch/operations/isDisabled"
export * from "@effect/core/io/RuntimeFlags/patch/operations/isEmpty"
export * from "@effect/core/io/RuntimeFlags/patch/operations/render"
// codegen:end
