// codegen:start {preset: barrel, include: ./operations/*.ts, prefix: "@effect/core/stm/TQueue"}
export * from "@effect/core/stm/TQueue/operations/awaitShutdown"
export * from "@effect/core/stm/TQueue/operations/bounded"
export * from "@effect/core/stm/TQueue/operations/capacity"
export * from "@effect/core/stm/TQueue/operations/dropping"
export * from "@effect/core/stm/TQueue/operations/isEmpty"
export * from "@effect/core/stm/TQueue/operations/isFull"
export * from "@effect/core/stm/TQueue/operations/isShutdown"
export * from "@effect/core/stm/TQueue/operations/make"
export * from "@effect/core/stm/TQueue/operations/offer"
export * from "@effect/core/stm/TQueue/operations/offerAll"
export * from "@effect/core/stm/TQueue/operations/peek"
export * from "@effect/core/stm/TQueue/operations/peekOption"
export * from "@effect/core/stm/TQueue/operations/poll"
export * from "@effect/core/stm/TQueue/operations/seek"
export * from "@effect/core/stm/TQueue/operations/shutdown"
export * from "@effect/core/stm/TQueue/operations/size"
export * from "@effect/core/stm/TQueue/operations/sliding"
export * from "@effect/core/stm/TQueue/operations/take"
export * from "@effect/core/stm/TQueue/operations/takeAll"
export * from "@effect/core/stm/TQueue/operations/takeBetween"
export * from "@effect/core/stm/TQueue/operations/takeN"
export * from "@effect/core/stm/TQueue/operations/takeRemainder"
export * from "@effect/core/stm/TQueue/operations/takeUpTo"
export * from "@effect/core/stm/TQueue/operations/unbounded"
// codegen:end
