// Generated by @effect/graphql-generator. Do not edit.
import * as Schema from "effect/Schema"

export const Int = Schema.Number.check(Schema.isInt32())

export const ID = Schema.String

/** An ISO-8601 encoded UTC date string. */
export const DateTime = Schema.DateTimeUtcFromString

/** An RFC 3986, RFC 3987, and RFC 6570 (level 4) compliant URI string. */
export const URI = Schema.URLFromString

/**
 * The possible states of an issue.
 *
 * - `CLOSED`: An issue that has been closed
 * - `OPEN`: An issue that is still open
 */
export const IssueState = Schema.Literals(["CLOSED", "OPEN"])
export type IssueState = typeof IssueState.Type

/** The possible `__typename` values of each interface and union the operations select from. */
export declare namespace Typename {
  /** Every possible `__typename` of interface `Node`. */
  export type Node = "Issue" | "PullRequest" | "Repository" | "User"
}
