// Generated by @effect/graphql-generator from viewer.graphql. Do not edit.
import { GraphQL, GraphQLGroup } from "effect/graphql"
import * as Schema from "effect/Schema"

/** `query Viewer` */
export const Viewer = GraphQL.query("Viewer", {
  document: "query Viewer{viewer{login name}}",
  result: Schema.Struct({
    /** The currently authenticated user. */
    viewer: Schema.Struct({
      /** The username used to login. */
      login: Schema.String,
      /** The user's public profile name. */
      name: Schema.NullOr(Schema.String)
    })
  })
})
export declare namespace Viewer {
  export type Variables = typeof Viewer.variables.Type
  export type Result = typeof Viewer.result.Type
}

/** Every operation in viewer.graphql. */
export const ViewerGroup = GraphQLGroup.make(Viewer)
