#!/usr/bin/env bash
rm -rf ./dist
rm -rf ./Bigint
rm -rf ./Either
rm -rf ./HashMap
rm -rf ./MutableRef
rm -rf ./Predicate
rm -rf ./Symbol
rm -rf ./Boolean
rm -rf ./Encoding
rm -rf ./HashSet
rm -rf ./NonEmptyIterable
rm -rf ./ReadonlyArray
rm -rf ./Tuple
rm -rf ./Brand
rm -rf ./Equal
rm -rf ./Inspectable
rm -rf ./Number
rm -rf ./ReadonlyRecord
rm -rf ./Types
rm -rf ./Chunk
rm -rf ./Equivalence
rm -rf ./List
rm -rf ./Option
rm -rf ./RedBlackTree
rm -rf ./Unify
rm -rf ./Context
rm -rf ./Function
rm -rf ./MutableHashMap
rm -rf ./Order
rm -rf ./SortedMap
rm -rf ./UtilsGen
rm -rf ./Data
rm -rf ./GlobalValue
rm -rf ./MutableHashSet
rm -rf ./Ordering
rm -rf ./SortedSet
rm -rf ./index
rm -rf ./Differ
rm -rf ./HKT
rm -rf ./MutableList
rm -rf ./PCGRandom
rm -rf ./String
rm -rf ./Duration
rm -rf ./Hash
rm -rf ./MutableQueue
rm -rf ./Pipeable
rm -rf ./Struct
