#!/usr/bin/env bash
rm -rf tsconfig.tsbuildinfo
rm -rf ./dist
rm -rf ./Bigint
rm -rf ./Either
rm -rf ./HashMap
rm -rf ./MutableRef
rm -rf ./Predicate
rm -rf ./Symbol
rm -rf ./Boolean
rm -rf ./Encoding
rm -rf ./HashSet
rm -rf ./NonEmptyIterable
rm -rf ./ReadonlyArray
rm -rf ./Tuple
rm -rf ./Brand
rm -rf ./Equal
rm -rf ./Inspectable
rm -rf ./Number
rm -rf ./ReadonlyRecord
rm -rf ./Types
rm -rf ./Chunk
rm -rf ./Equivalence
rm -rf ./List
rm -rf ./Option
rm -rf ./RedBlackTree
rm -rf ./Unify
rm -rf ./Context
rm -rf ./Function
rm -rf ./MutableHashMap
rm -rf ./Order
rm -rf ./SortedMap
rm -rf ./Utils
rm -rf ./Data
rm -rf ./GlobalValue
rm -rf ./MutableHashSet
rm -rf ./Ordering
rm -rf ./SortedSet
rm -rf ./index
rm -rf ./Differ
rm -rf ./HKT
rm -rf ./MutableList
rm -rf ./String
rm -rf ./Duration
rm -rf ./Hash
rm -rf ./MutableQueue
rm -rf ./Pipeable
rm -rf ./Struct
rm -rf ./Cache
rm -rf ./Hub
rm -rf ./Request
rm -rf ./Cause
rm -rf ./KeyedPool
rm -rf ./RequestBlock
rm -rf ./Clock
rm -rf ./Layer
rm -rf ./RequestResolver
rm -rf ./LogLevel
rm -rf ./Resource
rm -rf ./Config
rm -rf ./LogSpan
rm -rf ./Runtime
rm -rf ./ConfigError
rm -rf ./Logger
rm -rf ./RuntimeFlags
rm -rf ./ConfigProvider
rm -rf ./Metric
rm -rf ./RuntimeFlagsPatch
rm -rf ./ConfigProviderPathPatch
rm -rf ./MetricBoundaries
rm -rf ./Schedule
rm -rf ./ConfigSecret
rm -rf ./MetricHook
rm -rf ./ScheduleDecision
rm -rf ./Console
rm -rf ./MetricKey
rm -rf ./ScheduleInterval
rm -rf ./DefaultServices
rm -rf ./MetricKeyType
rm -rf ./ScheduleIntervals
rm -rf ./Deferred
rm -rf ./MetricLabel
rm -rf ./Scheduler
rm -rf ./Effect
rm -rf ./MetricPair
rm -rf ./Scope
rm -rf ./ExecutionStrategy
rm -rf ./MetricPolling
rm -rf ./ScopedCache
rm -rf ./Exit
rm -rf ./MetricRegistry
rm -rf ./ScopedRef
rm -rf ./Fiber
rm -rf ./MetricState
rm -rf ./Supervisor
rm -rf ./FiberId
rm -rf ./Pool
rm -rf ./SynchronizedRef
rm -rf ./FiberRef
rm -rf ./Queue
rm -rf ./Tracer
rm -rf ./FiberRefs
rm -rf ./Random
rm -rf ./FiberRefsPatch
rm -rf ./Ref
rm -rf ./FiberStatus
rm -rf ./Reloadable
rm -rf ./STM
rm -rf ./THub
rm -rf ./TQueue
rm -rf ./TRef
rm -rf ./TArray
rm -rf ./TMap
rm -rf ./TRandom
rm -rf ./TSemaphore
rm -rf ./TDeferred
rm -rf ./TPriorityQueue
rm -rf ./TReentrantLock
rm -rf ./TSet
rm -rf ./TestAnnotation
rm -rf ./TestAnnotationMap
rm -rf ./TestAnnotations
rm -rf ./TestClock
rm -rf ./TestConfig
rm -rf ./TestContext
rm -rf ./TestLive
rm -rf ./TestServices
rm -rf ./TestSized
