// Usage: node scripts/generate-character-encoding.ts /path/to/iconv-lite
// Mechanically imports mapping data only. Runtime codecs are implemented locally.
import { execFileSync } from "node:child_process"
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { resolve } from "node:path"

const upstream = resolve(process.argv[2] ?? "../iconv-lite")
const require = createRequire(resolve(upstream, "package.json"))
const revision = execFileSync("git", ["-C", upstream, "rev-parse", "HEAD"], { encoding: "utf8" }).trim()
const license = readFileSync(resolve(upstream, "LICENSE"), "utf8")
const directory = resolve("packages/effect/src/internal/characterEncoding")
mkdirSync(directory, { recursive: true })
const header =
  `/*\n * Mapping data from iconv-lite ${revision}.\n * Generated by scripts/generate-character-encoding.ts; do not edit.\n *\n${
    license.trim().split("\n").map((line) => ` * ${line}`).join("\n")
  }\n */\n`
const single = { ...require("./encodings/sbcs-data"), ...require("./encodings/sbcs-data-generated") }
const definitions: Record<string, string> = {}
const aliases: Record<string, string> = {}
for (const [name, value] of Object.entries(single)) {
  if (typeof value === "string") aliases[name] = value
  else if (typeof value === "object" && value !== null && "chars" in value) {
    definitions[name] = String(value.chars)
  }
}
writeFileSync(
  resolve(directory, "singleByteData.ts"),
  `${header}export const definitions: Readonly<Record<string, string>> = ${
    JSON.stringify(definitions)
  }\nexport const aliases: Readonly<Record<string, string>> = ${JSON.stringify(aliases)}\n`
)

const multi = require("./encodings/dbcs-data")
const names: Array<string> = []
const multiAliases: Record<string, string> = {}
for (const [name, value] of Object.entries(multi)) {
  if (typeof value === "string") multiAliases[name] = value
  else if (typeof value === "object" && value !== null && "table" in value) {
    const item = value as {
      table: () => unknown
      encodeAdd?: unknown
      encodeSkipVals?: unknown
      gb18030?: () => unknown
    }
    const data = {
      table: item.table(),
      encodeAdd: item.encodeAdd,
      encodeSkipVals: item.encodeSkipVals,
      ranges: item.gb18030?.()
    }
    names.push(name)
    writeFileSync(
      resolve(directory, `${name}Data.ts`),
      `${header}import type { Mapping } from "./types.ts"\nconst data: Mapping = ${
        JSON.stringify(data)
      }\nexport default data\n`
    )
  }
}
writeFileSync(
  resolve(directory, "multiByteData.ts"),
  `${header}import type { Mapping } from "./types.ts"\n${
    names.map((name) => `import ${name} from "./${name}Data.ts"`).join("\n")
  }\nexport const definitions: Readonly<Record<string, Mapping>> = { ${
    names.join(", ")
  } }\nexport const aliases: Readonly<Record<string, string>> = ${JSON.stringify(multiAliases)}\n`
)
console.log(
  `Imported ${Object.keys(definitions).length} single-byte and ${names.length} multibyte mappings from ${revision}`
)
