// Usage: node scripts/generate-character-encoding.ts
// Imports mapping data and generates explicit codec modules. Runtime codecs are implemented locally.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

if (process.argv.length > 2) {
  throw new Error("No arguments expected; uses the installed effect dev dependency iconv-lite")
}
const effectDirectory = fileURLToPath(new URL("../packages/effect/", import.meta.url))
const effectRequire = createRequire(resolve(effectDirectory, "package.json"))
const packagePath = effectRequire.resolve("iconv-lite/package.json")
const upstream = dirname(packagePath)
const require = createRequire(packagePath)
const revision = (require("./package.json") as { version: string }).version
const license = readFileSync(resolve(upstream, "LICENSE"), "utf8")
const directory = resolve(effectDirectory, "src/internal/characterEncoding")
mkdirSync(directory, { recursive: true })
const publicDirectory = resolve(effectDirectory, "src/encoding")
mkdirSync(publicDirectory, { recursive: true })
const header =
  `/*\n * Mapping data from iconv-lite ${revision}.\n * Generated by scripts/generate-character-encoding.ts; do not edit.\n *\n${
    license.trim().split("\n").map((line) => ` * ${line}`).join("\n")
  }\n */\n`
const single = { ...require("./encodings/sbcs-data"), ...require("./encodings/sbcs-data-generated") }
const definitions: Record<string, string> = {}
for (const [name, value] of Object.entries(single)) {
  if (typeof value === "object" && value !== null && "chars" in value) {
    definitions[name] = String(value.chars)
  }
}
for (const [name, chars] of Object.entries(definitions)) {
  writeFileSync(resolve(directory, name + "Data.ts"), header + "export default " + JSON.stringify(chars) + "\n")
}

const multi = require("./encodings/dbcs-data")
const names: Array<string> = []
for (const [name, value] of Object.entries(multi)) {
  if (typeof value === "object" && value !== null && "table" in value) {
    const item = value as {
      table: () => unknown
      encodeAdd?: unknown
      encodeSkipVals?: unknown
      gb18030?: () => unknown
    }
    const data = {
      table: item.table(),
      encodeAdd: item.encodeAdd,
      encodeSkipVals: item.encodeSkipVals,
      ranges: item.gb18030?.()
    }
    names.push(name)
    writeFileSync(
      resolve(directory, `${name}Data.ts`),
      `${header}import type { Mapping } from "./types.ts"\nconst data: Mapping = ${
        JSON.stringify(data)
      }\nexport default data\n`
    )
  }
}

const unicode = new Set(["utf8", "utf16le", "utf16be", "utf32le", "utf32be"])
const all = [...unicode, ...Object.keys(definitions), ...names].sort()
const special: Record<string, string> = {
  utf8: "Utf8",
  utf16le: "Utf16LE",
  utf16be: "Utf16BE",
  utf32le: "Utf32LE",
  utf32be: "Utf32BE",
  shiftjis: "ShiftJis",
  eucjp: "EucJp",
  big5hkscs: "Big5Hkscs",
  gbk: "Gbk",
  gb18030: "Gb18030"
}
const moduleName = (name: string): string =>
  special[name] ?? (/^cp125[0-8]$/.test(name) ? "Windows" + name.slice(2) : name[0].toUpperCase() + name.slice(1))
if (new Set(all.map(moduleName)).size !== all.length) throw new Error("Duplicate codec module names")
const doc = (text: string, category?: string) =>
  "/**\n * " + text + "\n *\n" + (category ? " * @category " + category + "\n" : "") + " * @since 4.0.0\n */\n"
const generated = "// Generated by scripts/generate-character-encoding.ts; do not edit.\n"
for (const name of all) {
  const isUnicode = unicode.has(name)
  const isSingle = Object.hasOwn(definitions, name)
  const engine = isSingle ? "SingleByte" : "MultiByte"
  const dataImport = isUnicode
    ? "import * as Unicode from \"../internal/characterEncoding/unicode.ts\"\n"
    : "import data from \"../internal/characterEncoding/" + name + "Data.ts\"\nimport { " + engine +
      " } from \"../internal/characterEncoding/" + (isSingle ? "singleByte" : "multiByte") + ".ts\"\n"
  const factory = isUnicode
    ? "() => ({ encoder: (options) => Unicode.encoder(\"" + name +
      "\", options), decoder: (options) => Unicode.decoder(\"" + name + "\", options) }), true"
    : "() => new " + engine + "(data)"

  const capitalizedName = name[0].toUpperCase() + name.slice(1).toUpperCase()
  const displayName = special[name] ? special[name].replace(/([A-Z])/g, "-$1").slice(1) : capitalizedName

  writeFileSync(
    resolve(publicDirectory, moduleName(name) + ".ts"),
    doc(displayName + " character encoding with typed failures and Effect streams.") + generated +
      "import type { CharacterEncodingError, Encoding, Options } from \"../CharacterEncoding.ts\"\n" +
      "import type * as Effect from \"../Effect.ts\"\n" +
      "import { make } from \"../internal/characterEncoding/codec.ts\"\n" +
      dataImport +
      "import * as Operators from \"../internal/characterEncoding/operators.ts\"\n" +
      "import type * as Stream from \"../Stream.ts\"\n\n" +
      doc("The " + name + " codec descriptor, for use with the CharacterEncoding operators.", "encodings") +
      "export const encoding: Encoding = /* @__PURE__ */ make(\"" + name + "\", " + factory + ")\n\n" +
      doc("Encodes a complete string to " + name + " bytes, throwing CharacterEncodingError on failure.", "encoding") +
      "export const encodeUnsafe = (text: string, options?: Options): Uint8Array =>\n" +
      "  Operators.encodeUnsafe(encoding, text, options)\n\n" +
      doc("Decodes complete " + name + " bytes to a string, throwing CharacterEncodingError on failure.", "decoding") +
      "export const decodeUnsafe = (bytes: Uint8Array, options?: Options): string =>\n" +
      "  Operators.decodeUnsafe(encoding, bytes, options)\n\n" +
      doc("Encodes a string to " + name + " bytes with conversion errors in the Effect error channel.", "encoding") +
      "export const encode = (text: string, options?: Options): Effect.Effect<Uint8Array, CharacterEncodingError> =>\n" +
      "  Operators.encode(encoding, text, options)\n\n" +
      doc("Decodes " + name + " bytes to a string with conversion errors in the Effect error channel.", "decoding") +
      "export const decode = (bytes: Uint8Array, options?: Options): Effect.Effect<string, CharacterEncodingError> =>\n" +
      "  Operators.decode(encoding, bytes, options)\n\n" +
      doc(
        "Encodes a stream of strings to " + name + " bytes incrementally, preserving codec state across chunks.",
        "streaming"
      ) +
      "export const encodeStream = (\n" +
      "  options?: Options\n" +
      "): <E, R>(self: Stream.Stream<string, E, R>) => Stream.Stream<Uint8Array, E | CharacterEncodingError, R> =>\n" +
      "  Operators.encodeStream(encoding, options)\n\n" +
      doc(
        "Decodes a stream of " + name + " bytes to strings incrementally, retaining partial sequences across chunks.",
        "streaming"
      ) +
      "export const decodeStream = (\n" +
      "  options?: Options\n" +
      "): <E, R>(self: Stream.Stream<Uint8Array, E, R>) => Stream.Stream<string, E | CharacterEncodingError, R> =>\n" +
      "  Operators.decodeStream(encoding, options)\n"
  )
}
console.log("Generated " + all.length + " explicit codec modules and mapping data from " + revision)
