/* oxlint-disable no-undef */
import { createHash } from "node:crypto"
import * as Fs from "fs/promises"

const version = "5.32.15"
const baseUrl = `https://unpkg.com/swagger-ui-dist@${version}/`
const checksums = {
  "swagger-ui-bundle.js": "a7e344f2770b2f07527ce828e0951626983b8f2dcdb7a826689c0232023f995b",
  "swagger-ui-standalone-preset.js": "1ad2ffd7a236dca4e570ce2ba2ef3de721d7553d4e7449db58df66cb294311e9",
  "swagger-ui.css": "d7f39f764aa18c7b47dd05b9af5613e373e4ac0f3557c2693d52d0abc2464d76",
  "swagger-ui-bundle.js.LICENSE.txt": "63818894e4b04cd0e3180d9cb20761e227a939121e7484f8e1d528227c756f89",
  "swagger-ui-standalone-preset.js.LICENSE.txt": "000580e4e2255ea6ccde0c47f6d75e2f703a1931298fde58756793b67c0daed9",
  "LICENSE": "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30",
  "NOTICE": "0d20d1adef18aee3f40dd258172155521ce702ac445cb5f7b7d60ed32dad2fb2"
}

const assets = Object.fromEntries(await Promise.all(Object.entries(checksums).map(async ([name, checksum]) => {
  const response = await fetch(`${baseUrl}${name}`)
  if (!response.ok) throw new Error(`Failed to fetch ${name}: ${response.status}`)
  const bytes = Buffer.from(await response.arrayBuffer())
  if (createHash("sha256").update(bytes).digest("hex") !== checksum) {
    throw new Error(`Checksum mismatch for ${name}`)
  }
  return [name, bytes.toString("utf8")]
})))

// Retain the upstream license and notices in the browser-delivered script.
const license = `/*! Swagger UI ${version}\n${assets.NOTICE}\n${assets.LICENSE.replaceAll("*/", "* /")}\n*/`
const inlineScript = (name) =>
  assets[name]
    .replace(/^\/\*! For license information[^\n]*\n/, assets[`${name}.LICENSE.txt`] + "\n")
    .replace(/\/\/# sourceMappingURL=.*$/gm, "")
const javascript = [license, inlineScript("swagger-ui-bundle.js"), inlineScript("swagger-ui-standalone-preset.js")].join("\n")
const css = assets["swagger-ui.css"].replace(/\/\*# sourceMappingURL=.*?\*\//g, "")

const source = `/* oxlint-disable no-undef */
// Generated by scripts/package-swagger.mjs from swagger-ui-dist@${version}.
// Source: ${baseUrl} (SHA-256 checksums are enforced by the generator).

/** @internal */
export const javascript =
  ${JSON.stringify(javascript)}

/** @internal */
export const css =
  ${JSON.stringify(css)}
`

await Fs.writeFile("packages/effect/src/unstable/httpapi/internal/httpApiSwagger.ts", source)
