/* oxlint-disable no-undef */
import { createHash } from "node:crypto"
import * as Fs from "fs/promises"

const version = "1.73.1"
// Use the published bundle rather than jsDelivr's dynamically minified .min.js.
const bundleUrl = `https://cdn.jsdelivr.net/npm/@scalar/api-reference@${version}/dist/browser/standalone.js`
const licenseUrl = "https://raw.githubusercontent.com/scalar/scalar/f701820a1592b93390faf8b605416da7ff81c08e/LICENSE"

const fetchAsset = async (url, checksum) => {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status}`)
  const bytes = Buffer.from(await response.arrayBuffer())
  if (createHash("sha256").update(bytes).digest("hex") !== checksum) {
    throw new Error(`Checksum mismatch for ${url}`)
  }
  return bytes.toString("utf8")
}

const [jsBundle, license] = await Promise.all([
  fetchAsset(bundleUrl, "62c34a0dda38945864011ebaf6e7fa7812a332429120d18922b34d01c4f7ccc8"),
  fetchAsset(licenseUrl, "380cd0a6ad700e1f821f2a509f0dd9ff835041cee2d43daf5dedc1adb2bcc620")
])
// Preserve upstream notices and include the full license in the delivered script.
const javascript = `/*! Scalar API Reference ${version}\n${license.replaceAll("*/", "* /")}*/\n${
  jsBundle.replace(/\/\/# sourceMappingURL=.*$/gm, "")
}`

const source = `/* oxlint-disable no-undef */
// Generated by scripts/package-scalar.mjs from @scalar/api-reference@${version}.
// Source: ${bundleUrl} (SHA-256 checksums are enforced by the generator).

/**
 * @internal
 */
export const javascript =
  ${JSON.stringify(javascript)}
`

await Fs.writeFile("packages/effect/src/http-api/internal/httpApiScalar.ts", source)
