// copyright https://github.com/frptools

export * from "./clone"
export * from "./empty"
export * from "./entries"
export * from "./filter"
export * from "./forEach"
export * from "./fromArray"
export * from "./fromIterable"
export * from "./fromNativeMap"
export * from "./fromObject"
export * from "./get"
export * from "./has"
export * from "./isEmpty"
export * from "./isEqual"
export * from "./isMap"
export * from "./keys"
export * from "./map"
export * from "./reduce"
export * from "./remove"
export * from "./set"
export * from "./size"
export * from "./update"
export * from "./updateMap"
export * from "./values"
