export * from "@fp-ts/data/Differ"
export * as ChunkPatch from "@fp-ts/data/Differ/ChunkPatch"
export * as ContextPatch from "@fp-ts/data/Differ/ContextPatch"
export * as HashMapPatch from "@fp-ts/data/Differ/HashMapPatch"
export * as HashSetPatch from "@fp-ts/data/Differ/HashSetPatch"
export * as OrPatch from "@fp-ts/data/Differ/OrPatch"
