// codegen:start {preset: barrel, include: ./operations/*.ts}
export * from "./operations/add"
export * from "./operations/beginMutation"
export * from "./operations/chain"
export * from "./operations/difference"
export * from "./operations/empty"
export * from "./operations/endMutation"
export * from "./operations/equal"
export * from "./operations/every"
export * from "./operations/filter"
export * from "./operations/forEach"
export * from "./operations/from"
export * from "./operations/has"
export * from "./operations/intersection"
export * from "./operations/isSubset"
export * from "./operations/make"
export * from "./operations/map"
export * from "./operations/mutate"
export * from "./operations/partition"
export * from "./operations/reduce"
export * from "./operations/remove"
export * from "./operations/size"
export * from "./operations/some"
export * from "./operations/toggle"
export * from "./operations/union"
export * from "./operations/values"
// codegen:end
