// codegen:start {preset: barrel, include: ./operations/*.ts, prefix: "@effect/core/stm/TRef"}
export * from "@effect/core/stm/TRef/operations/get"
export * from "@effect/core/stm/TRef/operations/getAndSet"
export * from "@effect/core/stm/TRef/operations/getAndUpdate"
export * from "@effect/core/stm/TRef/operations/getAndUpdateSome"
export * from "@effect/core/stm/TRef/operations/make"
export * from "@effect/core/stm/TRef/operations/makeCommit"
export * from "@effect/core/stm/TRef/operations/modify"
export * from "@effect/core/stm/TRef/operations/modifySome"
export * from "@effect/core/stm/TRef/operations/set"
export * from "@effect/core/stm/TRef/operations/unsafeGet"
export * from "@effect/core/stm/TRef/operations/unsafeMake"
export * from "@effect/core/stm/TRef/operations/unsafeSet"
export * from "@effect/core/stm/TRef/operations/update"
export * from "@effect/core/stm/TRef/operations/updateAndGet"
export * from "@effect/core/stm/TRef/operations/updateSome"
export * from "@effect/core/stm/TRef/operations/updateSomeAndGet"
// codegen:end
