export {
  Semigroup,
  fold,
  getDualSemigroup,
  getFirstSemigroup,
  getFunctionSemigroup,
  getIntercalateSemigroup,
  getJoinSemigroup,
  getLastSemigroup,
  getMeetSemigroup,
  getObjectSemigroup,
  getStructSemigroup,
  getTupleSemigroup,
  semigroupAll,
  semigroupAny,
  semigroupProduct,
  semigroupString,
  semigroupSum,
  semigroupVoid
} from "fp-ts/lib/Semigroup"
