// ets_tracing: off

export const _R: unique symbol = Symbol()
export const _E: unique symbol = Symbol()
export const _A: unique symbol = Symbol()
export const _U: unique symbol = Symbol()
export const _W: unique symbol = Symbol()
export const _L: unique symbol = Symbol()
export const _I: unique symbol = Symbol()
export const _O: unique symbol = Symbol()
export const _T: unique symbol = Symbol()
export const _C: unique symbol = Symbol()
export const _RIn: unique symbol = Symbol()
export const _ROut: unique symbol = Symbol()
export const _S1: unique symbol = Symbol()
export const _S2: unique symbol = Symbol()
