// codegen:start {preset: barrel, include: ./operations/*.ts, prefix: "@effect/core/io/Ref/Synchronized"}
export * from "@effect/core/io/Ref/Synchronized/operations/get"
export * from "@effect/core/io/Ref/Synchronized/operations/getAndSet"
export * from "@effect/core/io/Ref/Synchronized/operations/getAndUpdate"
export * from "@effect/core/io/Ref/Synchronized/operations/getAndUpdateEffect"
export * from "@effect/core/io/Ref/Synchronized/operations/getAndUpdateSome"
export * from "@effect/core/io/Ref/Synchronized/operations/getAndUpdateSomeEffect"
export * from "@effect/core/io/Ref/Synchronized/operations/make"
export * from "@effect/core/io/Ref/Synchronized/operations/modify"
export * from "@effect/core/io/Ref/Synchronized/operations/modifyEffect"
export * from "@effect/core/io/Ref/Synchronized/operations/modifySome"
export * from "@effect/core/io/Ref/Synchronized/operations/modifySomeEffect"
export * from "@effect/core/io/Ref/Synchronized/operations/set"
export * from "@effect/core/io/Ref/Synchronized/operations/update"
export * from "@effect/core/io/Ref/Synchronized/operations/updateAndGet"
export * from "@effect/core/io/Ref/Synchronized/operations/updateAndGetEffect"
export * from "@effect/core/io/Ref/Synchronized/operations/updateEffect"
export * from "@effect/core/io/Ref/Synchronized/operations/updateSome"
export * from "@effect/core/io/Ref/Synchronized/operations/updateSomeAndGet"
export * from "@effect/core/io/Ref/Synchronized/operations/updateSomeAndGetEffect"
export * from "@effect/core/io/Ref/Synchronized/operations/updateSomeEffect"
// codegen:end
