name: Cluster Integration
on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      EFFECT_CLUSTER_TESTS: "1"
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Pre-pull test container images
        run: |
          docker pull testcontainers/ryuk:0.14.0 &
          docker pull postgres:alpine &
          docker pull mysql:lts &
          wait

      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Test
        run: pnpm test-cluster
