name: Deploy website

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    if: github.repository_owner == 'Effect-Ts'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: ./.github/actions/deploy-website
        with:
          dispatch-token: ${{ secrets.WEBSITE_DISPATCH_TOKEN }}
