name: Deploy website

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    if: github.repository_owner == 'Effect-Ts'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-website
        with:
          dispatch-token: ${{ secrets.WEBSITE_DISPATCH_TOKEN }}
