name: TypeScript's Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  types:
    name: Types
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm test-types --target next
