name: Release queue input diagnostic
on:
  pull_request:

permissions: {}

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: Effect-TS/next-release-action@424506b3d0ee3412705866639f391fcd5a5c93fa
        with:
          github_token: ${{ github.token }}
          eligible_branches: "v4/next-minor,v4/next-major"
        env:
          NEXT_RELEASE_ACTION_DIAGNOSTIC: "true"
