/**
 * @since 0.6.0
 */

import * as Effect from "effect/Effect"
import * as FileSystem from "effect/FileSystem"
import * as Path from "effect/Path"
import * as Domain from "./Domain.ts"
import * as ExampleMetadata from "./ExampleMetadata.ts"
import type * as SemanticModel from "./SemanticModel.ts"

const markerName = ".effect-docgen"
const markerContent = "generated by @effect/docgen\n"

const filterJoin = (values: ReadonlyArray<string>): string => values.filter((value) => value.length > 0).join("-")

const exampleId = (example: SemanticModel.Example): string => {
  const namespaces = example.declarationPath.slice(0, -1).join("-")
  switch (example.declarationKind) {
    case "module":
      return "module"
    case "class":
      return "class"
    case "instanceMethod":
      return `${example.declarationPath[0]}-method`
    case "staticMethod":
      return `${example.declarationPath[0]}-staticmethod`
    case "interface":
      return filterJoin(["interface", namespaces])
    case "typeAlias":
      return filterJoin(["typealias", namespaces])
    case "namespace":
      return filterJoin(["namespace", example.declarationPath.slice(0, -1).join("-")])
    case "constant":
      return "constant"
    case "function":
      return "function"
    case "export":
      return "export"
  }
}

const declaration = (example: SemanticModel.Example): string =>
  example.declarationKind === "staticMethod"
    ? `${example.declarationPath[0]}.static.${example.declarationPath.slice(1).join(".")}`
    : example.declarationPath.join(".")

/**
 * Projects semantic examples into package-local TypeScript files.
 *
 * @category projections
 * @since 0.6.0
 */
export const project = (
  model: SemanticModel.SemanticModel
): Effect.Effect<ReadonlyArray<Domain.File>, Domain.DocgenError, Path.Path> =>
  Effect.gen(function*() {
    const path = yield* Path.Path
    const roots = new Map(model.packages.map((pkg) => [pkg.name, pkg.root] as const))
    return yield* Effect.forEach(model.examples, (example) =>
      Effect.gen(function*() {
        const packageRoot = roots.get(example.packageName)
        if (packageRoot === undefined) {
          return yield* new Domain.DocgenError({ message: `Missing package root for '${example.packageName}'` })
        }
        const packagePrefix = example.packageName.replace(/[^a-zA-Z0-9]+/g, "-")
        const prefix = filterJoin([packagePrefix, ...example.modulePath])
        const leaf = example.declarationKind === "module"
          ? example.modulePath.at(-1)!
          : example.declarationPath.at(-1)!
        return new Domain.File(
          path.join(packageRoot, "examples", `${prefix}-${exampleId(example)}-${leaf}-${example.index - 1}.ts`),
          `${
            ExampleMetadata.encode({
              name: example.name,
              packageName: example.packageName,
              sourcePath: example.sourcePath,
              declaration: declaration(example),
              index: example.index
            })
          }\n${example.source}`,
          true
        )
      }))
  })

/**
 * Refreshes marker-owned selected package outputs and writes projected examples.
 *
 * @category projections
 * @since 0.6.0
 */
export const write = (model: SemanticModel.SemanticModel) =>
  Effect.gen(function*() {
    const fs = yield* FileSystem.FileSystem
    const path = yield* Path.Path
    const files = yield* project(model)
    const selectedDirectories = model.packages.map((pkg) => path.join(pkg.root, "examples"))
    const outputDirectories = new Set(files.map((file) => path.dirname(file.path)))

    for (const directory of outputDirectories) {
      if ((yield* fs.exists(directory)) && !(yield* fs.exists(path.join(directory, markerName)))) {
        return yield* new Domain.DocgenError({
          message: `Refusing to overwrite unowned example directory '${directory}'`
        })
      }
    }
    for (const directory of selectedDirectories) {
      if (yield* fs.exists(path.join(directory, markerName))) {
        yield* fs.remove(directory, { recursive: true })
      }
    }
    for (const directory of outputDirectories) {
      yield* fs.makeDirectory(directory, { recursive: true })
      yield* fs.writeFileString(path.join(directory, markerName), markerContent)
    }
    yield* Effect.forEach(files, (file) => fs.writeFileString(file.path, file.content), { discard: true })
    yield* Effect.logInfo(`${files.length} example(s) found`)
  })
