/**
 * Emits per-document and shared modules from validated documents. Paths and
 * import specifiers are supplied by the caller; output needs no formatter.
 * Recursive input objects produce diagnostics instead of output.
 *
 * @internal
 */
import type * as Ast from "./Ast.ts"
import { type Diagnostic, make } from "./Diagnostic.ts"
import { print } from "./Printer.ts"
import * as SchemaModel from "./SchemaModel.ts"
import type { File } from "./Validate.ts"

/** One parsed document file holding only executable definitions. */
export interface DocumentFile extends File {
  /** Absolute path of the `.graphql.ts` emitted for this file. */
  readonly outputPath: string
  /** The source file's base name, used in the header. */
  readonly sourceName: string
}

/** A custom or built-in scalar mapped to a codec export. */
export interface ScalarMapping {
  /** The import specifier as written in the shared module. */
  readonly specifier: string
  readonly exportName: string
}

export interface Options {
  readonly schema: SchemaModel.Schema
  readonly files: ReadonlyArray<DocumentFile>
  /** Absolute path of the shared module. */
  readonly sharedPath: string
  readonly scalars: ReadonlyMap<string, ScalarMapping>
  /** The import specifier one generated file uses for another, from absolute paths. */
  readonly importSpecifier: (from: string, to: string) => string
}

export interface OutputFile {
  readonly path: string
  readonly contents: string
}

export interface Output {
  readonly files: ReadonlyArray<OutputFile>
  readonly errors: ReadonlyArray<Diagnostic>
  /** Custom scalars the operations reach that have no mapping, sorted by name. */
  readonly unmappedScalars: ReadonlyArray<string>
}

export const emit = (options: Options): Output => {
  const emitter = new Emitter(options)
  const errors = emitter.check()
  if (errors.length > 0) return { files: [], errors, unmappedScalars: [] }
  const emitted = options.files.map((file) => emitter.emitFile(file))
  const importErrors = emitted.flatMap((result) => result.errors)
  if (importErrors.length > 0) return { files: [], errors: importErrors, unmappedScalars: [] }
  const shared = emitter.emitShared()
  return { files: [shared.file, ...emitted.map((result) => result.file)], errors: [], unmappedScalars: shared.unmapped }
}

// -----------------------------------------------------------------------------
// Text helpers
// -----------------------------------------------------------------------------

/** How every generated file starts. Stale-output cleanup only deletes files that carry it. */
export const headerPrefix = "// Generated by @effect/graphql-generator"

const header = (sourceName: string | undefined): string =>
  sourceName === undefined
    ? `${headerPrefix}. Do not edit.`
    : `${headerPrefix} from ${sourceName}. Do not edit.`

/** Escapes `*\/` so text can't end the JSDoc comment it is written into. */
const escapeComment = (text: string): string => text.replace(/\*\//g, "*\\/")

const deprecation = (reason: string): string => escapeComment(reason.replace(/\s*\r?\n\s*/g, " "))

const descriptionLines = (description: string | undefined): Array<string> => {
  if (description === undefined) return []
  const lines = description.split(/\r\n|\r|\n/).map((line) => escapeComment(line.trimEnd()))
  while (lines.length > 0 && lines[0] === "") lines.shift()
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop()
  return lines
}

const docLines = (body: ReadonlyArray<string>, tags: ReadonlyArray<string>): Array<string> =>
  body.length > 0 && tags.length > 0 ? [...body, "", ...tags] : [...body, ...tags]

const jsdoc = (lines: ReadonlyArray<string>, indent: string): string => {
  if (lines.length === 0) return ""
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`
  return `${indent}/**\n${
    lines.map((line) => line === "" ? `${indent} *` : `${indent} * ${line}`).join("\n")
  }\n${indent} */\n`
}

const deprecatedTag = (reason: string | undefined): Array<string> =>
  reason === undefined ? [] : [`@deprecated ${deprecation(reason)}`]

const defaultTag = (value: SchemaModel.ConstValue | undefined): Array<string> =>
  value === undefined ? [] : [`@default ${escapeComment(printConstValue(value))}`]

/** A const value in GraphQL syntax, for `@default` tags. */
const printConstValue = (value: SchemaModel.ConstValue): string => {
  switch (value._tag) {
    case "IntValue":
    case "FloatValue":
    case "EnumValue":
      return value.value
    case "StringValue":
      return JSON.stringify(value.value)
    case "BooleanValue":
      return String(value.value)
    case "NullValue":
      return "null"
    case "ListValue":
      return `[${value.values.map(printConstValue).join(", ")}]`
    case "ObjectValue":
      return value.fields.length === 0
        ? "{}"
        : `{ ${value.fields.map((field) => `${field.name}: ${printConstValue(field.value)}`).join(", ")} }`
  }
}

const struct = (members: ReadonlyArray<string>, indent: string, schema = "Schema"): string =>
  members.length === 0 ? `${schema}.Struct({})` : `${schema}.Struct({\n${members.join(",\n")}\n${indent}})`

/** Writes out a type reference: `leaf` for its named type, `list` around list types, `nullable` around types without `!`. */
const typeRef = (
  type: SchemaModel.TypeRef,
  leaf: (name: string) => string,
  list: (element: string) => string,
  nullable: (inner: string) => string
): string => {
  const nonNull = (type: SchemaModel.NamedTypeRef | SchemaModel.ListTypeRef): string =>
    type._tag === "ListTypeRef" ? list(typeRef(type.ofType, leaf, list, nullable)) : leaf(type.name)
  return type._tag === "NonNullTypeRef" ? nonNull(type.ofType) : nullable(nonNull(type))
}

const typeSchema = (type: SchemaModel.TypeRef, leaf: (name: string) => string, schema = "Schema"): string =>
  typeRef(type, leaf, (element) => `${schema}.Array(${element})`, (inner) => `${schema}.NullOr(${inner})`)

/**
 * The Schema for a variable or input field: a nullable one, or a non-null one
 * with a default, is `optional`.
 */
const inputSchema = (
  type: SchemaModel.TypeRef,
  hasDefault: boolean,
  ref: (name: string) => string,
  schema = "Schema"
): string => {
  const expression = typeSchema(
    type,
    (name) => name === "String" || name === "Boolean" ? `${schema}.${name}` : ref(name),
    schema
  )
  return hasDefault || type._tag !== "NonNullTypeRef" ? `${schema}.optional(${expression})` : expression
}

/**
 * A struct key. `__proto__` is written as a computed key, because in an
 * object literal the plain form sets the prototype instead of a field.
 */
const propertyKey = (key: string): string => key === "__proto__" ? `["__proto__"]` : key

/** `issue-timeline` → `IssueTimeline`. */
const pascalCase = (text: string): string =>
  text.split(/[^A-Za-z0-9]+/).map((word) => word.slice(0, 1).toUpperCase() + word.slice(1)).join("")

/** `issue-timeline.graphql` → `IssueTimelineGroup`. */
const groupName = (sourceName: string): string => {
  const name = pascalCase(sourceName.replace(/\.graphql$/, ""))
  return `${/^[0-9]/.test(name) ? `_${name}` : name}Group`
}

const reservedWords: ReadonlySet<string> = new Set([
  "await break case catch class const continue debugger default delete do else enum export extends",
  "false finally for function if implements import in instanceof interface let new null package private",
  "protected public return static super switch this throw true try typeof var void while with yield"
].flatMap((line) => line.split(" ")))

/** Names a strict-mode module can't bind, though they are valid GraphQL names. */
const unbindable = (name: string): boolean => reservedWords.has(name) || name === "arguments" || name === "eval"

/** Names every per-file module imports, which operations and fragments can't take. */
const importedNames: ReadonlySet<string> = new Set(["Schema", "Shared", "GraphQL", "GraphQLGroup"])

const builtInSharedScalars: ReadonlyArray<string> = ["Int", "Float", "ID"]

const builtInScalarCodec = (name: string, schema: string): string => {
  switch (name) {
    case "Int":
      return `${schema}.Number.check(${schema}.isInt32())`
    case "Float":
      return `${schema}.Finite`
    default:
      return `${schema}.String`
  }
}

/** Every fragment spread in a selection set, through fields and inline fragments, in source order. */
const spreadsIn = (selectionSet: Ast.SelectionSet): Array<Ast.FragmentSpread> =>
  selectionSet.selections.flatMap((selection) =>
    selection._tag === "FragmentSpread"
      ? [selection]
      : selection.selectionSet === undefined
      ? []
      : spreadsIn(selection.selectionSet)
  )

// -----------------------------------------------------------------------------
// Emitter
// -----------------------------------------------------------------------------

interface FragmentEntry {
  readonly definition: Ast.FragmentDefinition
  readonly file: DocumentFile
}

/**
 * A selection together with where it came from. `via` is undefined when the
 * selection is written in the file being emitted; otherwise it is the spread
 * in that file through which a fragment from another file was written out
 * inline. `conditional` is set when the selection, or a fragment it came
 * through, has a `@skip` / `@include` with a variable condition.
 */
interface Sourced<S extends Ast.Selection> {
  readonly selection: S
  readonly via: Ast.FragmentSpread | undefined
  readonly conditional: boolean
}

/** A selection after inline fragments are flattened into their parent. */
type FlatSelection = Sourced<Ast.Field | Ast.FragmentSpread>

interface SpreadItem {
  readonly _tag: "Spread"
  readonly name: string
  readonly spread: Ast.FragmentSpread
  readonly via: Ast.FragmentSpread | undefined
}

type Item = { readonly _tag: "Field"; readonly key: string; readonly fields: Array<Sourced<Ast.Field>> } | SpreadItem

const written = (selections: ReadonlyArray<Ast.Selection>): Array<Sourced<Ast.Selection>> =>
  selections.map((selection) => ({ selection, via: undefined, conditional: false }))

/**
 * How `@skip` / `@include` decide a selection: a literal
 * condition is folded, so the selection is dropped or the directive ignored,
 * and a variable condition makes it conditional.
 */
const inclusion = (directives: ReadonlyArray<Ast.Directive>): "exclude" | "include" | "conditional" => {
  let result: "include" | "conditional" = "include"
  for (const directive of directives) {
    const name = directive.name.value
    if (name !== "skip" && name !== "include") continue
    const value = directive.arguments.find((argument) => argument.name.value === "if")?.value
    if (value?._tag === "BooleanValue") {
      if (value.value === (name === "skip")) return "exclude"
    } else {
      result = "conditional"
    }
  }
  return result
}

const isAbstract = (type: SchemaModel.NamedType): type is SchemaModel.InterfaceType | SchemaModel.UnionType =>
  type._tag === "InterfaceType" || type._tag === "UnionType"

/** The name a type takes in the shared module's `Typename` namespace. */
const typenameMember = (name: string): string => unbindable(name) ? `${name}_` : name

/** `prefix` followed by `"A" | "B"`, wrapped onto `|` lines when it doesn't fit in 120 columns. */
const literalUnion = (prefix: string, names: ReadonlyArray<string>, indent: string): string => {
  const literals = names.map((name) => JSON.stringify(name))
  const single = `${prefix}${literals.join(" | ")}`
  if (single.length <= 120) return single
  const lines: Array<string> = []
  let line = ""
  for (const literal of literals) {
    const next = line === "" ? `${indent}  | ${literal}` : `${line} | ${literal}`
    if (next.length > 120 && line !== "") {
      lines.push(line)
      line = `${indent}  | ${literal}`
    } else {
      line = next
    }
  }
  lines.push(line)
  return `${prefix.trimEnd()}\n${lines.join("\n")}`
}

interface FileContext {
  readonly file: DocumentFile
  usesSchema: boolean
  usesGraphQL: boolean
  usesShared: boolean
  /** Fragments imported from other files, by output path. */
  readonly imports: Map<string, Set<string>>
  /** For each imported fragment, the first spread in this file that led to the import. */
  readonly importedVia: Map<string, Ast.FragmentSpread>
  /** Fragments of this file referenced by the code being rendered. */
  localRefs: Set<string>
}

class Emitter {
  readonly schema: SchemaModel.Schema
  readonly fragments = new Map<string, FragmentEntry>()
  /** Named types the per-file modules reference through `Shared`. */
  readonly reached = new Set<string>()
  /** Interfaces and unions the per-file modules reference through `Shared.Typename`. */
  readonly reachedAbstract = new Set<string>()
  readonly fragmentKeyCache = new Map<string, ReadonlyArray<string>>()

  readonly options: Options

  constructor(options: Options) {
    this.options = options
    this.schema = options.schema
    for (const file of options.files) {
      for (const definition of file.document.definitions) {
        if (definition._tag === "FragmentDefinition") {
          this.fragments.set(definition.name.value, { definition, file })
        }
      }
    }
  }

  type(name: string): SchemaModel.NamedType {
    const type = this.schema.types.get(name)
    if (type === undefined) throw new Error(`@effect/graphql-generator: unknown type ${name} after validation`)
    return type
  }

  fieldDefinition(parent: SchemaModel.NamedType, name: string): SchemaModel.Field {
    const fields = parent._tag === "ObjectType" || parent._tag === "InterfaceType" ? parent.fields : []
    const field = fields.find((field) => field.name === name)
    if (field === undefined) {
      throw new Error(`@effect/graphql-generator: unknown field ${parent.name}.${name} after validation`)
    }
    return field
  }

  /** The object types a type stands for: itself, or an abstract type's possible types. */
  possibleTypes(name: string): ReadonlyArray<string> {
    const type = this.type(name)
    return isAbstract(type) ? type.possibleTypes : [name]
  }

  rootType(operation: Ast.OperationDefinition): string {
    switch (operation.operation) {
      case "query":
        return this.schema.queryType
      case "mutation":
        return this.schema.mutationType!
      case "subscription":
        return this.schema.subscriptionType!
    }
  }

  // ---------------------------------------------------------------------------
  // Checks
  // ---------------------------------------------------------------------------

  /** Names generated code can't use, recursive input objects and import cycles, sorted by file and position. */
  check(): ReadonlyArray<Diagnostic> {
    const errors: Array<{ readonly file: number; readonly offset: number; readonly message: string }> = []
    this.options.files.forEach((file, fileIndex) => {
      const report = (offset: number, message: string) => errors.push({ file: fileIndex, offset, message })
      const group = groupName(file.sourceName)
      const exportsGroup = file.document.definitions.some((definition) => definition._tag === "OperationDefinition")
      for (const definition of file.document.definitions) {
        if (definition._tag !== "OperationDefinition" && definition._tag !== "FragmentDefinition") continue
        const name = definition.name
        if (name !== undefined) {
          if (importedNames.has(name.value) || reservedWords.has(name.value)) {
            report(name.loc.start, `The name "${name.value}" is reserved in generated code; rename this definition.`)
          } else if (name.value === group && exportsGroup) {
            report(name.loc.start, `The name "${name.value}" is taken by the group this file exports.`)
          }
        }
        if (definition._tag === "OperationDefinition") {
          for (const variable of definition.variableDefinitions) {
            this.checkVariable(variable, report)
          }
        }
      }
    })
    errors.push(...this.importCycles())
    return errors
      .sort((a, b) => a.file - b.file || a.offset - b.offset)
      .map((error) => make(this.options.files[error.file]!.source, error.offset, error.message))
  }

  /**
   * Cycles in the imports between generated files. Every fragment reference
   * is read while its module initializes, so any cycle throws for some entry
   * point. Each cycle is reported once, at its first cross-file spread by file
   * order and then position. Every cross-file spread counts, including ones
   * the emitter would write out inline, so the rule doesn't depend on how a
   * selection set is merged.
   */
  importCycles(): Array<{ readonly file: number; readonly offset: number; readonly message: string }> {
    const files = this.options.files
    const indexOf = new Map(files.map((file, i) => [file, i] as const))
    const edges: Array<{ readonly from: number; readonly to: number; readonly spread: Ast.FragmentSpread }> = []
    const adjacent = files.map(() => new Set<number>())
    files.forEach((file, from) => {
      for (const definition of file.document.definitions) {
        if (definition._tag !== "OperationDefinition" && definition._tag !== "FragmentDefinition") continue
        for (const spread of spreadsIn(definition.selectionSet)) {
          const entry = this.fragments.get(spread.name.value)
          if (entry === undefined || entry.file === file) continue
          const to = indexOf.get(entry.file)!
          edges.push({ from, to, spread })
          adjacent[from]!.add(to)
        }
      }
    })

    // Tarjan's strongly connected components.
    const index: Array<number | undefined> = files.map(() => undefined)
    const low: Array<number> = files.map(() => 0)
    const onStack = files.map(() => false)
    const stack: Array<number> = []
    const components: Array<ReadonlySet<number>> = []
    let next = 0
    const connect = (v: number): void => {
      index[v] = low[v] = next++
      stack.push(v)
      onStack[v] = true
      for (const w of adjacent[v]!) {
        if (index[w] === undefined) {
          connect(w)
          low[v] = Math.min(low[v]!, low[w]!)
        } else if (onStack[w]) {
          low[v] = Math.min(low[v]!, index[w]!)
        }
      }
      if (low[v] === index[v]) {
        const component = new Set<number>()
        let w: number
        do {
          w = stack.pop()!
          onStack[w] = false
          component.add(w)
        } while (w !== v)
        if (component.size > 1) components.push(component)
      }
    }
    files.forEach((_, v) => {
      if (index[v] === undefined) connect(v)
    })

    return components.map((component) => {
      const first = edges
        .filter((edge) => component.has(edge.from) && component.has(edge.to))
        .sort((a, b) => a.from - b.from || a.spread.loc.start - b.spread.loc.start)[0]!
      // The shortest way back from the spread's target to the spreading file.
      const previous = new Map<number, number>([[first.to, -1]])
      const queue = [first.to]
      while (!previous.has(first.from)) {
        const v = queue.shift()!
        for (const w of adjacent[v]!) {
          if (component.has(w) && !previous.has(w)) {
            previous.set(w, v)
            queue.push(w)
          }
        }
      }
      const path: Array<number> = []
      for (let v = first.from; v !== -1; v = previous.get(v)!) path.unshift(v)
      const names = [first.from, ...path].map((i) => files[i]!.source.path)
      return {
        file: first.from,
        offset: first.spread.loc.start,
        message:
          `Fragment spread "...${first.spread.name.value}" makes the generated modules import each other in a cycle: ${
            names.join(" -> ")
          }. Move fragments between files so the imports don't form a cycle.`
      }
    })
  }

  checkVariable(variable: Ast.VariableDefinition, report: (offset: number, message: string) => void): void {
    const visiting = new Set<string>()
    const done = new Set<string>()
    const visit = (name: string): string | undefined => {
      const type = this.schema.types.get(name)
      if (type === undefined || type._tag !== "InputObjectType") return undefined
      if (visiting.has(name)) {
        return `Variable "$${variable.variable.name.value}" uses the recursive input object "${name}"; recursive input objects are not supported yet.`
      }
      if (done.has(name)) return undefined
      visiting.add(name)
      for (const field of type.fields) {
        const problem = visit(SchemaModel.namedTypeOf(field.type))
        if (problem !== undefined) return problem
      }
      visiting.delete(name)
      done.add(name)
      return undefined
    }
    const problem = visit(SchemaModel.namedTypeOf(SchemaModel.fromAstType(variable.type)))
    if (problem !== undefined) report(variable.loc.start, problem)
  }

  // ---------------------------------------------------------------------------
  // Result selections
  // ---------------------------------------------------------------------------

  /**
   * Whether a fragment on `condition` applies to `target`. A target that is an
   * object type is one concrete type. A target that is an interface or union
   * stands for the possible types no fragment names, so only a fragment
   * covering every one of its possible types applies.
   */
  applies(condition: string | undefined, target: string): boolean {
    if (condition === undefined || condition === target) return true
    const type = this.type(target)
    if (type._tag === "ObjectType") {
      const fragmentType = this.type(condition)
      return isAbstract(fragmentType) && fragmentType.possibleTypes.includes(target)
    }
    // Only an interface the target declares contributes fields the target has.
    return type._tag === "InterfaceType" && type.interfaces.includes(condition)
  }

  /**
   * Flattens a selection set for `target`: inline fragments and spreads that
   * apply to it are written into their parent and the rest are dropped,
   * excluded selections are dropped, and variable conditions are carried down.
   * A spread of a fragment on exactly the object type `target` is kept, unless
   * it is conditional, since `...Frag.fields` can't make its keys optional.
   */
  narrow(file: DocumentFile, selections: ReadonlyArray<Sourced<Ast.Selection>>, target: string): Array<FlatSelection> {
    const out: Array<FlatSelection> = []
    for (const { conditional: outer, selection, via } of selections) {
      const included = inclusion(selection.directives)
      if (included === "exclude") continue
      const conditional = outer || included === "conditional"
      switch (selection._tag) {
        case "Field":
          out.push({ selection, via, conditional })
          break
        case "InlineFragment":
          if (this.applies(selection.typeCondition?.name.value, target)) {
            out.push(...this.narrow(
              file,
              selection.selectionSet.selections.map((selection) => ({ selection, via, conditional })),
              target
            ))
          }
          break
        case "FragmentSpread": {
          const fragment = this.fragments.get(selection.name.value)!
          const condition = fragment.definition.typeCondition.name.value
          if (condition === target && this.type(target)._tag === "ObjectType" && !conditional) {
            out.push({ selection, via, conditional })
          } else if (this.applies(condition, target)) {
            out.push(...this.narrow(file, this.expand(file, fragment, selection, via, conditional), target))
          }
          break
        }
      }
    }
    return out
  }

  /** A fragment's selections, written out inline through `spread`. */
  expand(
    file: DocumentFile,
    fragment: FragmentEntry,
    spread: Ast.FragmentSpread,
    via: Ast.FragmentSpread | undefined,
    conditional: boolean
  ): Array<Sourced<Ast.Selection>> {
    // A local fragment's selections are written in this file; another file's come in through this spread.
    const through = fragment.file === file ? undefined : via ?? spread
    return fragment.definition.selectionSet.selections.map((selection) => ({ selection, via: through, conditional }))
  }

  group(flat: ReadonlyArray<FlatSelection>): Array<Item> {
    const items: Array<Item> = []
    const fields = new Map<string, Array<Sourced<Ast.Field>>>()
    const spreads = new Set<string>()
    for (const entry of flat) {
      const selection = entry.selection
      if (selection._tag === "Field") {
        const key = (selection.alias ?? selection.name).value
        const existing = fields.get(key)
        const sourced = { selection, via: entry.via, conditional: entry.conditional }
        if (existing === undefined) {
          const merged = [sourced]
          fields.set(key, merged)
          items.push({ _tag: "Field", key, fields: merged })
        } else {
          existing.push(sourced)
        }
      } else if (!spreads.has(selection.name.value)) {
        spreads.add(selection.name.value)
        items.push({ _tag: "Spread", name: selection.name.value, spread: selection, via: entry.via })
      }
    }
    return items
  }

  fragmentDefinition(name: string): Ast.FragmentDefinition {
    const entry = this.fragments.get(name)
    if (entry === undefined) throw new Error(`@effect/graphql-generator: unknown fragment ${name} after validation`)
    return entry.definition
  }

  /** Every response key a fragment on an object type contributes, through nested spreads. */
  fragmentKeys(name: string): ReadonlyArray<string> {
    const cached = this.fragmentKeyCache.get(name)
    if (cached !== undefined) return cached
    const entry = this.fragments.get(name)!
    const keys = new Set<string>()
    const flat = this.narrow(
      entry.file,
      written(entry.definition.selectionSet.selections),
      entry.definition.typeCondition.name.value
    )
    for (const item of this.group(flat)) {
      if (item._tag === "Field") keys.add(item.key)
      else for (const key of this.fragmentKeys(item.name)) keys.add(key)
    }
    const result = Array.from(keys)
    this.fragmentKeyCache.set(name, result)
    return result
  }

  /**
   * Groups a selection set for `target`, writing out inline every spread
   * whose keys overlap a sibling's or one of `reserved`.
   * The remaining spreads become `...Frag.fields`.
   */
  resolveItems(
    file: DocumentFile,
    selections: ReadonlyArray<Sourced<Ast.Selection>>,
    target: string,
    reserved: ReadonlyArray<string> = []
  ): Array<Item> {
    let flat = this.narrow(file, selections, target)
    for (;;) {
      const items = this.group(flat)
      const overlapping = items.find((item) => {
        if (item._tag !== "Spread") return false
        const others = new Set<string>(reserved)
        for (const other of items) {
          if (other === item) continue
          if (other._tag === "Field") others.add(other.key)
          else for (const key of this.fragmentKeys(other.name)) others.add(key)
        }
        return this.fragmentKeys(item.name).some((key) => others.has(key))
      })
      if (overlapping === undefined || overlapping._tag !== "Spread") return items
      const fragment = this.fragments.get(overlapping.name)!
      flat = flat.flatMap((entry) => {
        const selection = entry.selection
        if (selection._tag !== "FragmentSpread" || selection.name.value !== overlapping.name) return [entry]
        return this.narrow(file, this.expand(file, fragment, selection, entry.via, entry.conditional), target)
      })
    }
  }

  fragmentRef(ctx: FileContext, item: SpreadItem): string {
    const name = item.name
    const entry = this.fragments.get(name)!
    if (entry.file === ctx.file) {
      ctx.localRefs.add(name)
    } else {
      if (!ctx.importedVia.has(name)) ctx.importedVia.set(name, item.via ?? item.spread)
      let names = ctx.imports.get(entry.file.outputPath)
      if (names === undefined) {
        names = new Set()
        ctx.imports.set(entry.file.outputPath, names)
      }
      names.add(name)
    }
    return name
  }

  shared(ctx: FileContext, name: string): string {
    ctx.usesShared = true
    this.reached.add(name)
    return `Shared.${name}`
  }

  typename(ctx: FileContext, name: string): string {
    ctx.usesShared = true
    this.reachedAbstract.add(name)
    return `Shared.Typename.${typenameMember(name)}`
  }

  /**
   * The Schema for a selection set on `parentName`, starting on a line
   * indented by `indent`. A selection that is only one spread of a fragment
   * on exactly that type references the fragment unless `alwaysStruct` is
   * set.
   */
  selection(
    ctx: FileContext,
    parentName: string,
    selections: ReadonlyArray<Sourced<Ast.Selection>>,
    indent: string,
    alwaysStruct = false
  ): string {
    const parent = this.type(parentName)
    if (isAbstract(parent)) {
      const only = alwaysStruct ? undefined : this.onlySpread(selections, parentName)
      return only !== undefined ? this.fragmentRef(ctx, only) : this.abstractSelection(ctx, parent, selections, indent)
    }
    const items = this.resolveItems(ctx.file, selections, parentName)
    const only = items[0]
    if (!alwaysStruct && items.length === 1 && only!._tag === "Spread") {
      return this.fragmentRef(ctx, only!)
    }
    return this.structOf(ctx, parent, items, indent, `Schema.Literal(${JSON.stringify(parent.name)})`, false)
  }

  /** The one spread a selection set consists of, when it is an unconditional spread of a fragment on `parentName`. */
  onlySpread(selections: ReadonlyArray<Sourced<Ast.Selection>>, parentName: string): SpreadItem | undefined {
    const kept = selections.filter(({ selection }) => inclusion(selection.directives) !== "exclude")
    const only = kept[0]
    if (kept.length !== 1 || only!.selection._tag !== "FragmentSpread") return undefined
    const spread = only!.selection
    if (only!.conditional || inclusion(spread.directives) !== "include") return undefined
    if (this.fragmentDefinition(spread.name.value).typeCondition.name.value !== parentName) return undefined
    return { _tag: "Spread", name: spread.name.value, spread, via: only!.via }
  }

  /**
   * The object types a selection on an abstract type names through fragments
   * that don't apply to the type itself (see `applies`), in order of first
   * mention. Each gets its own member of the union, even when it is the only
   * possible type.
   */
  selectedTypes(
    parent: SchemaModel.InterfaceType | SchemaModel.UnionType,
    selections: ReadonlyArray<Sourced<Ast.Selection>>
  ): Array<string> {
    const all = parent.possibleTypes
    const selected: Array<string> = []
    const walk = (selections: ReadonlyArray<Ast.Selection>, scope: ReadonlyArray<string>): void => {
      for (const selection of selections) {
        if (selection._tag === "Field" || inclusion(selection.directives) === "exclude") continue
        const definition = selection._tag === "FragmentSpread"
          ? this.fragmentDefinition(selection.name.value)
          : selection
        const condition = definition.typeCondition?.name.value
        let next = scope
        if (!this.applies(condition, parent.name)) {
          const inScope = new Set(scope)
          next = this.possibleTypes(condition!).filter((name) => inScope.has(name))
          for (const name of next) if (!selected.includes(name)) selected.push(name)
        }
        walk(definition.selectionSet.selections, next)
      }
    }
    walk(selections.map(({ selection }) => selection), all)
    return selected
  }

  /**
   * A selection on an interface or union: one struct per
   * selected object type with `__typename: Schema.Literal("T")`, and one for
   * every other possible type with `GraphQL.otherTypename`.
   */
  abstractSelection(
    ctx: FileContext,
    parent: SchemaModel.InterfaceType | SchemaModel.UnionType,
    selections: ReadonlyArray<Sourced<Ast.Selection>>,
    indent: string
  ): string {
    ctx.usesGraphQL = true
    const selected = this.selectedTypes(parent, selections)
    const others = `GraphQL.otherTypename<${this.typename(ctx, parent.name)}>()([${
      selected.map((name) => JSON.stringify(name)).join(", ")
    }])`
    const member = (type: SchemaModel.NamedType, typename: string, indent: string) =>
      this.structOf(
        ctx,
        type,
        this.resolveItems(ctx.file, selections, type.name, ["__typename"]),
        indent,
        typename,
        true
      )
    if (selected.length === 0) return member(parent, others, indent)
    const memberIndent = `${indent}  `
    const members = [
      ...selected.map((name) => member(this.type(name), `Schema.Literal(${JSON.stringify(name)})`, memberIndent)),
      member(parent, others, memberIndent)
    ]
    return `Schema.Union([\n${members.map((member) => `${memberIndent}${member}`).join(",\n")}\n${indent}])`
  }

  /**
   * A struct for `items` on `parent`. `typename` is the Schema for a
   * selected `__typename`; with `discriminated` set, `__typename` comes first
   * whether or not it was selected.
   */
  structOf(
    ctx: FileContext,
    parent: SchemaModel.NamedType,
    items: ReadonlyArray<Item>,
    indent: string,
    typename: string,
    discriminated: boolean
  ): string {
    ctx.usesSchema = true
    const memberIndent = `${indent}  `
    const members: Array<string> = discriminated ? [`${memberIndent}__typename: ${typename}`] : []
    for (const item of items) {
      if (item._tag === "Spread") {
        members.push(`${memberIndent}...${this.fragmentRef(ctx, item)}.fields`)
      } else if (!(discriminated && item.key === "__typename")) {
        members.push(this.resultMember(ctx, parent, item.key, item.fields, memberIndent, typename))
      }
    }
    return struct(members, indent)
  }

  resultMember(
    ctx: FileContext,
    parent: SchemaModel.NamedType,
    key: string,
    fields: ReadonlyArray<Sourced<Ast.Field>>,
    indent: string,
    typename: string
  ): string {
    const name = fields[0]!.selection.name.value
    const optional = (expression: string): string =>
      fields.every((field) => field.conditional) ? `Schema.optionalKey(${expression})` : expression
    if (name === "__typename") return `${indent}${propertyKey(key)}: ${optional(typename)}`
    const definition = this.fieldDefinition(parent, name)
    const typeName = SchemaModel.namedTypeOf(definition.type)
    const type = this.type(typeName)
    const inner = type._tag === "ObjectType" || isAbstract(type)
      ? this.selection(
        ctx,
        typeName,
        // The parent's key covers its only occurrence's condition. With several
        // occurrences, the parent can be present because of another one, so
        // each occurrence's condition carries over to the children it adds.
        fields.flatMap(({ conditional, selection: field, via }) =>
          (field.selectionSet?.selections ?? []).map((selection) => ({
            selection,
            via,
            conditional: conditional && fields.length > 1
          }))
        ),
        indent
      )
      : this.resultLeaf(ctx, type)
    const doc = docLines(descriptionLines(definition.description), deprecatedTag(definition.deprecationReason))
    const expression = optional(typeSchema(definition.type, () => inner))
    return `${jsdoc(doc, indent)}${indent}${propertyKey(key)}: ${expression}`
  }

  resultLeaf(ctx: FileContext, type: SchemaModel.NamedType): string {
    if (type.name === "String" || type.name === "Boolean") return `Schema.${type.name}`
    if (type._tag === "EnumType") {
      ctx.usesGraphQL = true
      return `GraphQL.enumLiterals(${this.shared(ctx, type.name)}.literals)`
    }
    return this.shared(ctx, type.name)
  }

  // ---------------------------------------------------------------------------
  // Per-file modules
  // ---------------------------------------------------------------------------

  /**
   * Emits one per-file module. Fails with a located error when the module
   * would import a fragment named like the group it exports; the import is
   * found from the code actually emitted, so a spread written out inline
   * counts only for the fragments it really brings in.
   */
  emitFile(file: DocumentFile): { readonly file: OutputFile; readonly errors: ReadonlyArray<Diagnostic> } {
    const ctx: FileContext = {
      file,
      usesSchema: false,
      usesGraphQL: false,
      usesShared: false,
      imports: new Map(),
      importedVia: new Map(),
      localRefs: new Set()
    }

    const fragments = new Map<string, { readonly code: string; readonly refs: ReadonlySet<string> }>()
    const operations: Array<string> = []
    const operationNames: Array<string> = []
    for (const definition of file.document.definitions) {
      ctx.localRefs = new Set()
      if (definition._tag === "FragmentDefinition") {
        fragments.set(definition.name.value, { code: this.emitFragment(ctx, definition), refs: ctx.localRefs })
      } else if (definition._tag === "OperationDefinition") {
        operations.push(this.emitOperation(ctx, definition))
        operationNames.push(definition.name!.value)
      }
    }

    // Fragments are classes, so each one follows the fragments of this file it uses.
    const ordered: Array<string> = []
    const placed = new Set<string>()
    const place = (name: string): void => {
      if (placed.has(name)) return
      placed.add(name)
      for (const ref of fragments.get(name)!.refs) place(ref)
      ordered.push(fragments.get(name)!.code)
    }
    for (const name of fragments.keys()) place(name)

    const blocks = [...ordered, ...operations]
    const group = groupName(file.sourceName)
    const errors: Array<Diagnostic> = []
    if (operationNames.length > 0) {
      blocks.push(
        `/** Every operation in ${file.sourceName}. */\nexport const ${group} = GraphQLGroup.make(${
          operationNames.join(", ")
        })`
      )
      const via = ctx.importedVia.get(group)
      if (via !== undefined) {
        errors.push(make(
          file.source,
          via.loc.start,
          `Fragment "${group}" from ${
            this.fragments.get(group)!.file.source.path
          } can't be imported here: the name is taken by the group this file exports.`
        ))
      }
    }

    const imports: Array<string> = []
    const graphql = [...(ctx.usesGraphQL ? ["GraphQL"] : []), ...(operationNames.length > 0 ? ["GraphQLGroup"] : [])]
    if (graphql.length > 0) imports.push(`import { ${graphql.join(", ")} } from "effect/graphql"`)
    if (ctx.usesSchema) imports.push(`import * as Schema from "effect/Schema"`)
    const fragmentImports = Array.from(ctx.imports, ([path, names]) => ({
      specifier: this.options.importSpecifier(file.outputPath, path),
      names: Array.from(names).sort()
    })).sort((a, b) => a.specifier < b.specifier ? -1 : a.specifier > b.specifier ? 1 : 0)
    for (const { names, specifier } of fragmentImports) {
      imports.push(`import { ${names.join(", ")} } from ${JSON.stringify(specifier)}`)
    }
    if (ctx.usesShared) {
      imports.push(
        `import * as Shared from ${
          JSON.stringify(this.options.importSpecifier(file.outputPath, this.options.sharedPath))
        }`
      )
    }

    return {
      file: {
        path: file.outputPath,
        contents: `${[header(file.sourceName), ...imports].join("\n")}\n\n${blocks.join("\n\n")}\n`
      },
      errors
    }
  }

  /**
   * A fragment on an object type is an Opaque class; one on an interface or
   * union is a `Schema.Union` and a type alias.
   */
  emitFragment(ctx: FileContext, definition: Ast.FragmentDefinition): string {
    const name = definition.name.value
    const type = this.type(definition.typeCondition.name.value)
    ctx.usesSchema = true
    const description = definition.description?.value ?? type.description
    const doc = docLines([`\`fragment ${name} on ${type.name}\``], descriptionLines(description))
    const selections = written(definition.selectionSet.selections)
    if (isAbstract(type)) {
      const body = this.abstractSelection(ctx, type, selections, "")
      return `${jsdoc(doc, "")}export const ${name} = ${body}\nexport type ${name} = typeof ${name}.Type`
    }
    const body = this.selection(ctx, type.name, selections, "", true)
    return `${jsdoc(doc, "")}export class ${name} extends Schema.Opaque<${name}>()(${body}) {}`
  }

  emitOperation(ctx: FileContext, definition: Ast.OperationDefinition): string {
    const name = definition.name!.value
    const root = this.rootType(definition)
    ctx.usesGraphQL = true
    const doc = docLines(
      [`\`${definition.operation} ${name}\``],
      descriptionLines(definition.description?.value)
    )
    const lines = [`  document: ${JSON.stringify(this.document(definition))},`]
    if (definition.variableDefinitions.length > 0) {
      const members = definition.variableDefinitions.map((variable) => {
        const defaultValue = variable.defaultValue === undefined
          ? undefined
          : SchemaModel.fromAstConstValue(variable.defaultValue)
        const type = SchemaModel.fromAstType(variable.type)
        const expression = inputSchema(type, defaultValue !== undefined, (name) => this.shared(ctx, name))
        ctx.usesSchema ||= expression.includes("Schema.")
        const variableDoc = docLines(descriptionLines(variable.description?.value), defaultTag(defaultValue))
        return `${jsdoc(variableDoc, "    ")}    ${propertyKey(variable.variable.name.value)}: ${expression}`
      })
      lines.push(`  variables: {\n${members.join(",\n")}\n  },`)
    }
    lines.push(`  result: ${this.selection(ctx, root, written(definition.selectionSet.selections), "  ")}`)
    return [
      `${jsdoc(doc, "")}export const ${name} = GraphQL.${definition.operation}(${JSON.stringify(name)}, {`,
      ...lines,
      "})",
      `export declare namespace ${name} {`,
      `  export type Variables = typeof ${name}.variables.Type`,
      `  export type Result = typeof ${name}.result.Type`,
      "}"
    ].join("\n")
  }

  /**
   * The operation printed compactly, followed by every fragment it uses in
   * order of first use, with `__typename` added to every
   * selection on an interface or union that doesn't already select it.
   */
  document(operation: Ast.OperationDefinition): string {
    const used: Array<Ast.FragmentDefinition> = []
    const seen = new Set<string>()
    const collect = (selectionSet: Ast.SelectionSet): void => {
      for (const selection of selectionSet.selections) {
        if (selection._tag === "FragmentSpread") {
          if (!seen.has(selection.name.value)) {
            seen.add(selection.name.value)
            used.push(this.fragmentDefinition(selection.name.value))
          }
        } else if (selection.selectionSet !== undefined) {
          collect(selection.selectionSet)
        }
      }
    }
    collect(operation.selectionSet)
    for (let i = 0; i < used.length; i++) collect(used[i]!.selectionSet)
    return print({
      _tag: "Document",
      definitions: [
        { ...operation, selectionSet: this.withTypename(operation.selectionSet, this.rootType(operation)) },
        ...used.map((fragment) => ({
          ...fragment,
          selectionSet: this.withTypename(fragment.selectionSet, fragment.typeCondition.name.value)
        }))
      ],
      loc: operation.loc
    })
  }

  /**
   * Adds `__typename` to a selection set on an interface or union. Inline
   * fragments share their parent's response object, so the one added there
   * covers them (`inline`).
   */
  withTypename(selectionSet: Ast.SelectionSet, parentName: string, inline = false): Ast.SelectionSet {
    const parent = this.type(parentName)
    const selections = selectionSet.selections.map((selection): Ast.Selection => {
      switch (selection._tag) {
        case "Field": {
          if (selection.selectionSet === undefined) return selection
          const definition = this.fieldDefinition(parent, selection.name.value)
          return {
            ...selection,
            selectionSet: this.withTypename(selection.selectionSet, SchemaModel.namedTypeOf(definition.type))
          }
        }
        case "InlineFragment":
          return {
            ...selection,
            selectionSet: this.withTypename(
              selection.selectionSet,
              selection.typeCondition?.name.value ?? parentName,
              true
            )
          }
        case "FragmentSpread":
          return selection
      }
    })
    const selectsTypename = selections.some((selection) =>
      selection._tag === "Field" && selection.alias === undefined && selection.name.value === "__typename" &&
      selection.directives.length === 0
    )
    if (inline || !isAbstract(parent) || selectsTypename) return { ...selectionSet, selections }
    const loc = selectionSet.loc
    const typename: Ast.Field = {
      _tag: "Field",
      alias: undefined,
      name: { _tag: "Name", value: "__typename", loc },
      arguments: [],
      directives: [],
      selectionSet: undefined,
      loc
    }
    return { ...selectionSet, selections: [typename, ...selections] }
  }

  // ---------------------------------------------------------------------------
  // Shared module
  // ---------------------------------------------------------------------------

  /** The shared module, and the custom scalars it holds without a mapping. */
  emitShared(): { readonly file: OutputFile; readonly unmapped: ReadonlyArray<string> } {
    // Close over input objects: each one reaches the types of all its fields.
    const inputs: Array<SchemaModel.InputObjectType> = []
    const all = new Set<string>()
    const visit = (name: string): void => {
      if (all.has(name)) return
      all.add(name)
      const type = this.type(name)
      if (type._tag !== "InputObjectType") return
      for (const field of type.fields) visit(SchemaModel.namedTypeOf(field.type))
      inputs.push(type)
    }
    for (const name of Array.from(this.reached).sort()) visit(name)
    all.delete("String")
    all.delete("Boolean")

    const byName = Array.from(all).sort()
    const builtIns = builtInSharedScalars.filter((name) => all.has(name))
    const scalars = byName.filter((name) =>
      this.type(name)._tag === "ScalarType" && !SchemaModel.builtInScalarNames.includes(name)
    )
    const enums = byName.flatMap((name) => {
      const type = this.type(name)
      return type._tag === "EnumType" ? [type] : []
    })

    // Each type is exported under its GraphQL name, which per-file modules read
    // as `Shared.<name>`. A name the module can't bind gets a local alias,
    // and the module's own imports take names no type uses.
    const taken = new Set<string>([...byName, "Typename"])
    const allocate = (candidate: string): string => {
      let name = candidate
      for (let i = 2; taken.has(name) || unbindable(name); i++) name = `${candidate}${i}`
      taken.add(name)
      return name
    }
    const locals = new Map<string, string>()
    for (const name of byName) {
      if (!unbindable(name)) continue
      let local = `${name}_`
      while (taken.has(local)) local = `${local}_`
      taken.add(local)
      locals.set(name, local)
    }
    const local = (name: string): string => locals.get(name) ?? name
    const schema = allocate("Schema")

    let usesSchema = false
    const modules = new Map<string, string>()
    const moduleName = (specifier: string): string => {
      if (specifier === "effect/Schema") {
        usesSchema = true
        return schema
      }
      const existing = modules.get(specifier)
      if (existing !== undefined) return existing
      const candidate = pascalCase(specifier.split("/").pop()!.replace(/\.[^.]*$/, ""))
      const name = allocate(candidate === "" || /^[0-9]/.test(candidate) ? "Scalars" : candidate)
      modules.set(specifier, name)
      return name
    }
    const scalarCodec = (name: string, fallback: string): string => {
      const mapping = this.options.scalars.get(name)
      if (mapping === undefined) {
        usesSchema = true
        return fallback
      }
      return `${moduleName(mapping.specifier)}.${mapping.exportName}`
    }
    /**
     * A documented declaration, exported under the GraphQL name: directly, or
     * through `export { alias as Name }` when the name can't be bound.
     * `declaration` puts `exported` before each statement it writes.
     */
    const declare = (
      name: string,
      doc: ReadonlyArray<string>,
      declaration: (binding: string, exported: string) => string
    ): string => {
      const binding = local(name)
      return binding === name
        ? `${jsdoc(doc, "")}${declaration(name, "export ")}`
        : `${jsdoc(doc, "")}${declaration(binding, "")}\nexport { ${binding} as ${name} }`
    }

    const blocks: Array<string> = []
    for (const name of [...builtIns, ...scalars]) {
      const codec = scalarCodec(name, builtIns.includes(name) ? builtInScalarCodec(name, schema) : `${schema}.Json`)
      blocks.push(declare(name, descriptionLines(this.type(name).description), (b, e) => `${e}const ${b} = ${codec}`))
    }
    for (const type of enums) {
      usesSchema = true
      const values = type.values.map((value) => {
        const description = descriptionLines(value.description).join(" ")
        const deprecated = value.deprecationReason === undefined
          ? ""
          : ` Deprecated: ${deprecation(value.deprecationReason)}`
        return `- \`${value.name}\`${description === "" ? "" : `: ${description}`}${deprecated}`
      })
      const literals = type.values.map((value) => JSON.stringify(value.name)).join(", ")
      blocks.push(declare(
        type.name,
        docLines(descriptionLines(type.description), values),
        (b, e) => `${e}const ${b} = ${schema}.Literals([${literals}])\n${e}type ${b} = typeof ${b}.Type`
      ))
    }
    for (const type of inputs) {
      usesSchema = true
      const doc = descriptionLines(type.description)
      if (type.oneOf) {
        blocks.push(declare(type.name, doc, (b, e) => oneOfDeclaration(type, b, e, schema, local)))
        continue
      }
      const members = type.fields.map((field) => {
        const fieldDoc = docLines(
          descriptionLines(field.description),
          [...deprecatedTag(field.deprecationReason), ...defaultTag(field.defaultValue)]
        )
        return `${jsdoc(fieldDoc, "  ")}  ${propertyKey(field.name)}: ${
          inputSchema(field.type, field.defaultValue !== undefined, local, schema)
        }`
      })
      const body = struct(members, "", schema)
      blocks.push(declare(type.name, doc, (b, e) => `${e}class ${b} extends ${schema}.Opaque<${b}>()(${body}) {}`))
    }

    if (this.reachedAbstract.size > 0) {
      const members = Array.from(this.reachedAbstract).sort().map((name) => {
        const kind = this.type(name)._tag === "InterfaceType" ? "interface" : "union"
        const doc = `  /** Every possible \`__typename\` of ${kind} \`${name}\`. */\n`
        return `${doc}${literalUnion(`  export type ${typenameMember(name)} = `, this.possibleTypes(name), "  ")}`
      })
      blocks.push(
        `/** The possible \`__typename\` values of each interface and union the operations select from. */\n` +
          `export declare namespace Typename {\n${members.join("\n")}\n}`
      )
    }

    const imports: Array<string> = []
    if (usesSchema) imports.push(`import * as ${schema} from "effect/Schema"`)
    for (const [specifier, name] of modules) {
      imports.push(`import * as ${name} from ${JSON.stringify(specifier)}`)
    }
    const body = blocks.length === 0 ? "export {}" : blocks.join("\n\n")
    return {
      file: { path: this.options.sharedPath, contents: `${[header(undefined), ...imports].join("\n")}\n\n${body}\n` },
      unmapped: scalars.filter((name) => !this.options.scalars.has(name))
    }
  }
}

/**
 * A `@oneOf` input object: a `Schema.Union` with one
 * struct per field, each with that field required and non-null and every
 * other field `optionalKey(Never)`, so an input with two keys or none fails to
 * encode. A class can't extend `Opaque` over a union, so it is an Opaque const
 * with the type written out beside it.
 */
const oneOfDeclaration = (
  type: SchemaModel.InputObjectType,
  binding: string,
  exported: string,
  schema: string,
  ref: (name: string) => string
): string => {
  const required = (field: SchemaModel.InputValue): SchemaModel.TypeRef =>
    field.type._tag === "NonNullTypeRef" ? field.type : { _tag: "NonNullTypeRef", ofType: field.type }
  const structs = type.fields.map((selected) => {
    const members = type.fields.map((field) => {
      if (field !== selected) return `    ${propertyKey(field.name)}: ${schema}.optionalKey(${schema}.Never)`
      const doc = docLines(descriptionLines(field.description), deprecatedTag(field.deprecationReason))
      return `${jsdoc(doc, "    ")}    ${propertyKey(field.name)}: ${inputSchema(required(field), false, ref, schema)}`
    })
    return `  ${struct(members, "  ", schema)}`
  })
  const alternatives = type.fields.map((selected) =>
    `  | { ${
      type.fields.map((field) =>
        field === selected
          ? `readonly ${propertyKey(field.name)}: ${inputTypeText(required(field), ref)}`
          : `readonly ${propertyKey(field.name)}?: never`
      ).join("; ")
    } }`
  )
  return `${exported}const ${binding} = ${schema}.Opaque<${binding}>()(${schema}.Union([\n${
    structs.join(",\n")
  }\n]))\n` +
    `${exported}type ${binding} =\n${alternatives.join("\n")}`
}

/** The decoded TypeScript type of an input, as written in the shared module. */
const inputTypeText = (type: SchemaModel.TypeRef, ref: (name: string) => string): string =>
  typeRef(
    type,
    (name) => name === "String" || name === "Boolean" ? name.toLowerCase() : `typeof ${ref(name)}.Type`,
    (element) => `ReadonlyArray<${element}>`,
    (inner) => `${inner} | null`
  )
