/**
 * Emits the per-file `.graphql.ts` modules and the shared module from a
 * validated set of executable documents (EFF-1831, EFF-1832).
 *
 * The emitter is pure: paths and import specifiers are worked out by the
 * caller and passed in. Output uses one fixed style with no formatter.
 *
 * Stage 4 covers selections on object types only. Selections on interfaces
 * and unions, `@skip` / `@include`, `@oneOf` input objects, recursive input
 * objects and subscriptions are reported as located errors and nothing is
 * emitted.
 *
 * @internal
 */
import type * as Ast from "./Ast.ts"
import { type Diagnostic, make } from "./Diagnostic.ts"
import { print } from "./Printer.ts"
import * as SchemaModel from "./SchemaModel.ts"
import type { File } from "./Validate.ts"

/** One parsed document file holding only executable definitions. */
export interface DocumentFile extends File {
  /** Absolute path of the `.graphql.ts` emitted for this file. */
  readonly outputPath: string
  /** The source file's base name, used in the header. */
  readonly sourceName: string
}

/** A custom or built-in scalar mapped to a codec export. */
export interface ScalarMapping {
  /** The import specifier as written in the shared module. */
  readonly specifier: string
  readonly exportName: string
}

export interface Options {
  readonly schema: SchemaModel.Schema
  readonly files: ReadonlyArray<DocumentFile>
  /** Absolute path of the shared module. */
  readonly sharedPath: string
  readonly scalars: ReadonlyMap<string, ScalarMapping>
  /** The import specifier one generated file uses for another, from absolute paths. */
  readonly importSpecifier: (from: string, to: string) => string
}

export interface OutputFile {
  readonly path: string
  readonly contents: string
}

export interface Output {
  readonly files: ReadonlyArray<OutputFile>
  readonly errors: ReadonlyArray<Diagnostic>
  /** Custom scalars the operations reach that have no mapping, sorted by name. */
  readonly unmappedScalars: ReadonlyArray<string>
}

export const emit = (options: Options): Output => {
  const emitter = new Emitter(options)
  const errors = emitter.check()
  if (errors.length > 0) return { files: [], errors, unmappedScalars: [] }
  const files = options.files.map((file) => emitter.emitFile(file))
  const shared = emitter.emitShared()
  return { files: [shared, ...files], errors: [], unmappedScalars: emitter.unmappedScalars() }
}

// -----------------------------------------------------------------------------
// Text helpers
// -----------------------------------------------------------------------------

const header = (sourceName: string | undefined): string =>
  sourceName === undefined
    ? "// Generated by @effect/graphql-generator. Do not edit."
    : `// Generated by @effect/graphql-generator from ${sourceName}. Do not edit.`

const descriptionLines = (description: string | undefined): Array<string> => {
  if (description === undefined) return []
  const lines = description.split(/\r\n|\r|\n/).map((line) => line.trimEnd().replace(/\*\//g, "*\\/"))
  while (lines.length > 0 && lines[0] === "") lines.shift()
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop()
  return lines
}

/** Body lines followed by tag lines, separated by a blank line when both are present. */
const docLines = (body: ReadonlyArray<string>, tags: ReadonlyArray<string>): Array<string> =>
  body.length > 0 && tags.length > 0 ? [...body, "", ...tags] : [...body, ...tags]

const jsdoc = (lines: ReadonlyArray<string>, indent: string): string => {
  if (lines.length === 0) return ""
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`
  return `${indent}/**\n${
    lines.map((line) => line === "" ? `${indent} *` : `${indent} * ${line}`).join("\n")
  }\n${indent} */\n`
}

const deprecatedTag = (reason: string | undefined): Array<string> =>
  reason === undefined ? [] : [`@deprecated ${reason.replace(/\s*\r?\n\s*/g, " ").replace(/\*\//g, "*\\/")}`]

const defaultTag = (value: SchemaModel.ConstValue | undefined): Array<string> =>
  value === undefined ? [] : [`@default ${printConstValue(value).replace(/\*\//g, "*\\/")}`]

/** A const value in GraphQL syntax, for `@default` tags. */
const printConstValue = (value: SchemaModel.ConstValue): string => {
  switch (value._tag) {
    case "IntValue":
    case "FloatValue":
    case "EnumValue":
      return value.value
    case "StringValue":
      return JSON.stringify(value.value)
    case "BooleanValue":
      return String(value.value)
    case "NullValue":
      return "null"
    case "ListValue":
      return `[${value.values.map(printConstValue).join(", ")}]`
    case "ObjectValue":
      return value.fields.length === 0
        ? "{}"
        : `{ ${value.fields.map((field) => `${field.name}: ${printConstValue(field.value)}`).join(", ")} }`
  }
}

const struct = (members: ReadonlyArray<string>, indent: string, schema = "Schema"): string =>
  members.length === 0 ? `${schema}.Struct({})` : `${schema}.Struct({\n${members.join(",\n")}\n${indent}})`

/**
 * A struct key. `__proto__` is written as a computed key, because in an
 * object literal the plain form sets the prototype instead of a field.
 */
const propertyKey = (key: string): string => key === "__proto__" ? `["__proto__"]` : key

/** `issue-timeline.graphql` → `IssueTimeline`. */
const pascalCase = (fileName: string): string => {
  const words = fileName.replace(/\.graphql$/, "").split(/[^A-Za-z0-9]+/).filter((word) => word.length > 0)
  const name = words.map((word) => word[0]!.toUpperCase() + word.slice(1)).join("")
  return /^[0-9]/.test(name) ? `_${name}` : name
}

const reservedWords: ReadonlySet<string> = new Set([
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield"
])

/** Names a strict-mode module can't bind, though they are valid GraphQL names. */
const unbindable = (name: string): boolean => reservedWords.has(name) || name === "arguments" || name === "eval"

/** Names every per-file module imports, which operations and fragments can't take. */
const importedNames: ReadonlySet<string> = new Set(["Schema", "Shared", "GraphQL", "GraphQLGroup"])

const builtInSharedScalars: ReadonlyArray<string> = ["Int", "Float", "ID"]

const builtInScalarCodec = (name: string, schema: string): string => {
  switch (name) {
    case "Int":
      return `${schema}.Number.check(${schema}.isInt32())`
    case "Float":
      return `${schema}.Finite`
    default:
      return `${schema}.String`
  }
}

/** Every fragment spread in a selection set, through fields and inline fragments, in source order. */
const spreadsIn = (selectionSet: Ast.SelectionSet): Array<Ast.FragmentSpread> =>
  selectionSet.selections.flatMap((selection) =>
    selection._tag === "FragmentSpread"
      ? [selection]
      : selection.selectionSet === undefined
      ? []
      : spreadsIn(selection.selectionSet)
  )

// -----------------------------------------------------------------------------
// Emitter
// -----------------------------------------------------------------------------

interface FragmentEntry {
  readonly definition: Ast.FragmentDefinition
  readonly file: DocumentFile
}

/** A selection after inline fragments are flattened into their parent. */
type FlatSelection = Ast.Field | Ast.FragmentSpread

type Item =
  | { readonly _tag: "Field"; readonly key: string; readonly fields: Array<Ast.Field> }
  | { readonly _tag: "Spread"; readonly name: string }

interface FileContext {
  readonly file: DocumentFile
  usesSchema: boolean
  usesGraphQL: boolean
  usesGroup: boolean
  usesShared: boolean
  /** Fragments imported from other files, by output path. */
  readonly imports: Map<string, Set<string>>
  /** Fragments of this file referenced by the code being rendered. */
  localRefs: Set<string>
}

class Emitter {
  readonly schema: SchemaModel.Schema
  readonly fragments = new Map<string, FragmentEntry>()
  /** Named types the per-file modules reference through `Shared`. */
  readonly reached = new Set<string>()
  readonly fragmentKeyCache = new Map<string, ReadonlyArray<string>>()
  sharedNames: ReadonlyArray<string> = []

  readonly options: Options

  constructor(options: Options) {
    this.options = options
    this.schema = options.schema
    for (const file of options.files) {
      for (const definition of file.document.definitions) {
        if (definition._tag === "FragmentDefinition") {
          this.fragments.set(definition.name.value, { definition, file })
        }
      }
    }
  }

  type(name: string): SchemaModel.NamedType {
    const type = this.schema.types.get(name)
    if (type === undefined) throw new Error(`@effect/graphql-generator: unknown type ${name} after validation`)
    return type
  }

  objectType(name: string): SchemaModel.ObjectType {
    const type = this.type(name)
    if (type._tag !== "ObjectType") throw new Error(`@effect/graphql-generator: ${name} is not an object type`)
    return type
  }

  fieldDefinition(parent: SchemaModel.ObjectType, name: string): SchemaModel.Field {
    const field = parent.fields.find((field) => field.name === name)
    if (field === undefined) {
      throw new Error(`@effect/graphql-generator: unknown field ${parent.name}.${name} after validation`)
    }
    return field
  }

  rootType(operation: Ast.OperationDefinition): string {
    switch (operation.operation) {
      case "query":
        return this.schema.queryType
      case "mutation":
        return this.schema.mutationType!
      case "subscription":
        return this.schema.subscriptionType!
    }
  }

  // ---------------------------------------------------------------------------
  // Stage-5 features and naming
  // ---------------------------------------------------------------------------

  check(): ReadonlyArray<Diagnostic> {
    const errors: Array<{ file: number; offset: number; diagnostic: Diagnostic }> = []
    this.options.files.forEach((file, fileIndex) => {
      const report = (offset: number, message: string) =>
        errors.push({ file: fileIndex, offset, diagnostic: make(file.source, offset, message) })
      const groupName = `${pascalCase(file.sourceName)}Group`
      const exportsGroup = file.document.definitions.some((definition) => definition._tag === "OperationDefinition")
      let importReported = false
      for (const definition of file.document.definitions) {
        if (definition._tag !== "OperationDefinition" && definition._tag !== "FragmentDefinition") continue
        const name = definition.name
        if (name !== undefined) {
          if (importedNames.has(name.value) || reservedWords.has(name.value)) {
            report(name.loc.start, `The name "${name.value}" is reserved in generated code; rename this definition.`)
          } else if (name.value === groupName && exportsGroup) {
            report(name.loc.start, `The name "${name.value}" is taken by the group this file exports.`)
          }
        }
        // An imported fragment would bind the group's name too.
        if (exportsGroup && !importReported) {
          for (const spread of spreadsIn(definition.selectionSet)) {
            const entry = this.fragments.get(spread.name.value)
            if (entry !== undefined && entry.file !== file && spread.name.value === groupName) {
              report(
                spread.loc.start,
                `Fragment "${spread.name.value}" from ${entry.file.source.path} can't be imported here: the name is taken by the group this file exports.`
              )
              importReported = true
              break
            }
          }
        }
        if (definition._tag === "OperationDefinition") {
          if (definition.operation === "subscription") {
            report(definition.loc.start, `Subscription "${name?.value}" is not supported yet.`)
            continue
          }
          for (const variable of definition.variableDefinitions) {
            this.checkVariable(variable, report)
          }
          this.checkSelections(this.objectType(this.rootType(definition)), definition.selectionSet, report)
        } else {
          const condition = this.type(definition.typeCondition.name.value)
          if (condition._tag !== "ObjectType") {
            report(
              definition.typeCondition.loc.start,
              `Fragment "${definition.name.value}" is on ${
                kindName(condition)
              } "${condition.name}"; interfaces and unions are not supported yet.`
            )
            continue
          }
          this.checkSelections(condition, definition.selectionSet, report)
        }
      }
    })
    for (const cycle of this.importCycles()) {
      errors.push({
        file: cycle.file,
        offset: cycle.offset,
        diagnostic: make(this.options.files[cycle.file]!.source, cycle.offset, cycle.message)
      })
    }
    return errors.sort((a, b) => a.file - b.file || a.offset - b.offset).map((entry) => entry.diagnostic)
  }

  /**
   * Cycles in the imports between generated files. Every fragment reference
   * is read while its module initializes, so any cycle throws for some entry
   * point. Each cycle is reported once, at its first cross-file spread by file
   * order and then position. Every cross-file spread counts, including ones
   * the emitter would write out inline, so the rule doesn't depend on how a
   * selection set is merged.
   */
  importCycles(): Array<{ readonly file: number; readonly offset: number; readonly message: string }> {
    const files = this.options.files
    const indexOf = new Map(files.map((file, i) => [file, i] as const))
    const edges: Array<{ readonly from: number; readonly to: number; readonly spread: Ast.FragmentSpread }> = []
    const adjacent = files.map(() => new Set<number>())
    files.forEach((file, from) => {
      for (const definition of file.document.definitions) {
        if (definition._tag !== "OperationDefinition" && definition._tag !== "FragmentDefinition") continue
        for (const spread of spreadsIn(definition.selectionSet)) {
          const entry = this.fragments.get(spread.name.value)
          if (entry === undefined || entry.file === file) continue
          const to = indexOf.get(entry.file)!
          edges.push({ from, to, spread })
          adjacent[from]!.add(to)
        }
      }
    })

    // Tarjan's strongly connected components.
    const index: Array<number | undefined> = files.map(() => undefined)
    const low: Array<number> = files.map(() => 0)
    const onStack = files.map(() => false)
    const stack: Array<number> = []
    const components: Array<ReadonlySet<number>> = []
    let next = 0
    const connect = (v: number): void => {
      index[v] = low[v] = next++
      stack.push(v)
      onStack[v] = true
      for (const w of adjacent[v]!) {
        if (index[w] === undefined) {
          connect(w)
          low[v] = Math.min(low[v]!, low[w]!)
        } else if (onStack[w]) {
          low[v] = Math.min(low[v]!, index[w]!)
        }
      }
      if (low[v] === index[v]) {
        const component = new Set<number>()
        let w: number
        do {
          w = stack.pop()!
          onStack[w] = false
          component.add(w)
        } while (w !== v)
        if (component.size > 1) components.push(component)
      }
    }
    files.forEach((_, v) => {
      if (index[v] === undefined) connect(v)
    })

    return components.map((component) => {
      const first = edges
        .filter((edge) => component.has(edge.from) && component.has(edge.to))
        .sort((a, b) => a.from - b.from || a.spread.loc.start - b.spread.loc.start)[0]!
      // The shortest way back from the spread's target to the spreading file.
      const previous = new Map<number, number>([[first.to, -1]])
      const queue = [first.to]
      while (!previous.has(first.from)) {
        const v = queue.shift()!
        for (const w of adjacent[v]!) {
          if (component.has(w) && !previous.has(w)) {
            previous.set(w, v)
            queue.push(w)
          }
        }
      }
      const path: Array<number> = []
      for (let v = first.from; v !== -1; v = previous.get(v)!) path.unshift(v)
      const names = [first.from, ...path].map((i) => files[i]!.source.path)
      return {
        file: first.from,
        offset: first.spread.loc.start,
        message:
          `Fragment spread "...${first.spread.name.value}" makes the generated modules import each other in a cycle: ${
            names.join(" -> ")
          }. Move fragments between files so the imports don't form a cycle.`
      }
    })
  }

  checkVariable(variable: Ast.VariableDefinition, report: (offset: number, message: string) => void): void {
    const visiting = new Set<string>()
    const done = new Set<string>()
    const visit = (name: string): string | undefined => {
      const type = this.schema.types.get(name)
      if (type === undefined || type._tag !== "InputObjectType") return undefined
      if (type.oneOf) {
        return `Variable "$${variable.variable.name.value}" uses the @oneOf input object "${name}"; @oneOf input objects are not supported yet.`
      }
      if (visiting.has(name)) {
        return `Variable "$${variable.variable.name.value}" uses the recursive input object "${name}"; recursive input objects are not supported yet.`
      }
      if (done.has(name)) return undefined
      visiting.add(name)
      for (const field of type.fields) {
        const problem = visit(SchemaModel.namedTypeOf(field.type))
        if (problem !== undefined) return problem
      }
      visiting.delete(name)
      done.add(name)
      return undefined
    }
    const problem = visit(SchemaModel.namedTypeOf(SchemaModel.fromAstType(variable.type)))
    if (problem !== undefined) report(variable.loc.start, problem)
  }

  checkSelections(
    parent: SchemaModel.ObjectType,
    selectionSet: Ast.SelectionSet,
    report: (offset: number, message: string) => void
  ): void {
    for (const selection of selectionSet.selections) {
      for (const directive of selection.directives) {
        if (directive.name.value === "skip" || directive.name.value === "include") {
          report(directive.loc.start, `The @${directive.name.value} directive is not supported yet.`)
        }
      }
      switch (selection._tag) {
        case "Field": {
          if (selection.name.value === "__typename" || selection.selectionSet === undefined) break
          const field = this.fieldDefinition(parent, selection.name.value)
          const type = this.type(SchemaModel.namedTypeOf(field.type))
          if (type._tag === "ObjectType") {
            this.checkSelections(type, selection.selectionSet, report)
          } else {
            report(
              selection.loc.start,
              `Field "${selection.name.value}" selects from ${
                kindName(type)
              } "${type.name}"; interfaces and unions are not supported yet.`
            )
          }
          break
        }
        case "InlineFragment": {
          const condition = selection.typeCondition?.name.value
          if (condition !== undefined && condition !== parent.name) {
            report(
              selection.loc.start,
              `Inline fragments on "${condition}" inside "${parent.name}" are not supported yet.`
            )
            break
          }
          this.checkSelections(parent, selection.selectionSet, report)
          break
        }
        case "FragmentSpread":
          break
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Result selections
  // ---------------------------------------------------------------------------

  flatten(selections: ReadonlyArray<Ast.Selection>): Array<FlatSelection> {
    const out: Array<FlatSelection> = []
    for (const selection of selections) {
      if (selection._tag === "InlineFragment") out.push(...this.flatten(selection.selectionSet.selections))
      else out.push(selection)
    }
    return out
  }

  group(flat: ReadonlyArray<FlatSelection>): Array<Item> {
    const items: Array<Item> = []
    const fields = new Map<string, Array<Ast.Field>>()
    const spreads = new Set<string>()
    for (const selection of flat) {
      if (selection._tag === "Field") {
        const key = (selection.alias ?? selection.name).value
        const existing = fields.get(key)
        if (existing === undefined) {
          const merged = [selection]
          fields.set(key, merged)
          items.push({ _tag: "Field", key, fields: merged })
        } else {
          existing.push(selection)
        }
      } else if (!spreads.has(selection.name.value)) {
        spreads.add(selection.name.value)
        items.push({ _tag: "Spread", name: selection.name.value })
      }
    }
    return items
  }

  fragmentDefinition(name: string): Ast.FragmentDefinition {
    const entry = this.fragments.get(name)
    if (entry === undefined) throw new Error(`@effect/graphql-generator: unknown fragment ${name} after validation`)
    return entry.definition
  }

  /** Every response key a fragment contributes, through nested spreads. */
  fragmentKeys(name: string): ReadonlyArray<string> {
    const cached = this.fragmentKeyCache.get(name)
    if (cached !== undefined) return cached
    const keys = new Set<string>()
    for (const item of this.group(this.flatten(this.fragmentDefinition(name).selectionSet.selections))) {
      if (item._tag === "Field") keys.add(item.key)
      else for (const key of this.fragmentKeys(item.name)) keys.add(key)
    }
    const result = Array.from(keys)
    this.fragmentKeyCache.set(name, result)
    return result
  }

  /**
   * Groups a selection set, writing out inline every spread whose keys
   * overlap a sibling's (EFF-1831 point 3). The remaining spreads become
   * `...Frag.fields`.
   */
  resolveItems(selections: ReadonlyArray<Ast.Selection>): Array<Item> {
    let flat = this.flatten(selections)
    for (;;) {
      const items = this.group(flat)
      const overlapping = items.find((item) => {
        if (item._tag !== "Spread") return false
        const others = new Set<string>()
        for (const other of items) {
          if (other === item) continue
          if (other._tag === "Field") others.add(other.key)
          else for (const key of this.fragmentKeys(other.name)) others.add(key)
        }
        return this.fragmentKeys(item.name).some((key) => others.has(key))
      })
      if (overlapping === undefined || overlapping._tag !== "Spread") return items
      const replacement = this.flatten(this.fragmentDefinition(overlapping.name).selectionSet.selections)
      flat = flat.flatMap((selection) =>
        selection._tag === "FragmentSpread" && selection.name.value === overlapping.name ? replacement : [selection]
      )
    }
  }

  fragmentRef(ctx: FileContext, name: string): string {
    const entry = this.fragments.get(name)!
    if (entry.file === ctx.file) {
      ctx.localRefs.add(name)
    } else {
      let names = ctx.imports.get(entry.file.outputPath)
      if (names === undefined) {
        names = new Set()
        ctx.imports.set(entry.file.outputPath, names)
      }
      names.add(name)
    }
    return name
  }

  shared(ctx: FileContext, name: string): string {
    ctx.usesShared = true
    this.reached.add(name)
    return `Shared.${name}`
  }

  /**
   * The Schema for a selection set on an object type, starting on a line
   * indented by `indent`. A selection that is only one spread references the
   * fragment unless `alwaysStruct` is set.
   */
  selection(
    ctx: FileContext,
    parent: SchemaModel.ObjectType,
    selections: ReadonlyArray<Ast.Selection>,
    indent: string,
    alwaysStruct = false
  ): string {
    const items = this.resolveItems(selections)
    const only = items[0]
    if (!alwaysStruct && items.length === 1 && only!._tag === "Spread") {
      return this.fragmentRef(ctx, only!.name)
    }
    ctx.usesSchema = true
    const memberIndent = `${indent}  `
    const members = items.map((item) =>
      item._tag === "Spread"
        ? `${memberIndent}...${this.fragmentRef(ctx, item.name)}.fields`
        : this.resultMember(ctx, parent, item.key, item.fields, memberIndent)
    )
    return struct(members, indent)
  }

  resultMember(
    ctx: FileContext,
    parent: SchemaModel.ObjectType,
    key: string,
    fields: ReadonlyArray<Ast.Field>,
    indent: string
  ): string {
    const name = fields[0]!.name.value
    if (name === "__typename") {
      ctx.usesSchema = true
      return `${indent}${propertyKey(key)}: Schema.Literal(${JSON.stringify(parent.name)})`
    }
    const definition = this.fieldDefinition(parent, name)
    const type = this.type(SchemaModel.namedTypeOf(definition.type))
    const inner = type._tag === "ObjectType"
      ? this.selection(
        ctx,
        type,
        fields.flatMap((field) => field.selectionSet?.selections ?? []),
        indent
      )
      : this.resultLeaf(ctx, type)
    const doc = docLines(descriptionLines(definition.description), deprecatedTag(definition.deprecationReason))
    return `${jsdoc(doc, indent)}${indent}${propertyKey(key)}: ${this.wrapResult(ctx, definition.type, inner)}`
  }

  resultLeaf(ctx: FileContext, type: SchemaModel.NamedType): string {
    switch (type.name) {
      case "String":
        ctx.usesSchema = true
        return "Schema.String"
      case "Boolean":
        ctx.usesSchema = true
        return "Schema.Boolean"
    }
    if (type._tag === "EnumType") {
      ctx.usesGraphQL = true
      return `GraphQL.enumLiterals(${this.shared(ctx, type.name)}.literals)`
    }
    return this.shared(ctx, type.name)
  }

  wrapResult(ctx: FileContext, type: SchemaModel.TypeRef, inner: string): string {
    const nonNull = (type: SchemaModel.NamedTypeRef | SchemaModel.ListTypeRef): string =>
      type._tag === "ListTypeRef" ? `Schema.Array(${this.wrapResult(ctx, type.ofType, inner)})` : inner
    if (type._tag === "NonNullTypeRef") {
      if (type.ofType._tag === "ListTypeRef") ctx.usesSchema = true
      return nonNull(type.ofType)
    }
    ctx.usesSchema = true
    return `Schema.NullOr(${nonNull(type)})`
  }

  // ---------------------------------------------------------------------------
  // Inputs
  // ---------------------------------------------------------------------------

  /**
   * The Schema for a variable or input field (EFF-1832 points 2 to 4):
   * nullable is `optional(NullOr(T))`, non-null with a default is
   * `optional(T)`.
   */
  input(type: SchemaModel.TypeRef, hasDefault: boolean, ref: (name: string) => string, schema = "Schema"): string {
    const named = (type: SchemaModel.NamedTypeRef | SchemaModel.ListTypeRef): string => {
      if (type._tag === "ListTypeRef") return `${schema}.Array(${element(type.ofType)})`
      switch (type.name) {
        case "String":
          return `${schema}.String`
        case "Boolean":
          return `${schema}.Boolean`
        default:
          return ref(type.name)
      }
    }
    const element = (type: SchemaModel.TypeRef): string =>
      type._tag === "NonNullTypeRef" ? named(type.ofType) : `${schema}.NullOr(${named(type)})`
    if (type._tag === "NonNullTypeRef") {
      return hasDefault ? `${schema}.optional(${named(type.ofType)})` : named(type.ofType)
    }
    return `${schema}.optional(${schema}.NullOr(${named(type)}))`
  }

  // ---------------------------------------------------------------------------
  // Per-file modules
  // ---------------------------------------------------------------------------

  emitFile(file: DocumentFile): OutputFile {
    const ctx: FileContext = {
      file,
      usesSchema: false,
      usesGraphQL: false,
      usesGroup: false,
      usesShared: false,
      imports: new Map(),
      localRefs: new Set()
    }

    const fragments = new Map<string, { readonly code: string; readonly refs: ReadonlySet<string> }>()
    const operations: Array<string> = []
    const operationNames: Array<string> = []
    for (const definition of file.document.definitions) {
      if (definition._tag === "FragmentDefinition") {
        ctx.localRefs = new Set()
        const code = this.emitFragment(ctx, definition)
        fragments.set(definition.name.value, { code, refs: ctx.localRefs })
      } else if (definition._tag === "OperationDefinition") {
        ctx.localRefs = new Set()
        operations.push(this.emitOperation(ctx, definition))
        operationNames.push(definition.name!.value)
      }
    }

    // Fragments are classes, so each one follows the fragments of this file it uses.
    const ordered: Array<string> = []
    const placed = new Set<string>()
    const place = (name: string): void => {
      if (placed.has(name)) return
      placed.add(name)
      for (const ref of fragments.get(name)!.refs) place(ref)
      ordered.push(fragments.get(name)!.code)
    }
    for (const name of fragments.keys()) place(name)

    const blocks = [...ordered, ...operations]
    if (operationNames.length > 0) {
      ctx.usesGroup = true
      blocks.push(
        `/** Every operation in ${file.sourceName}. */\nexport const ${
          pascalCase(file.sourceName)
        }Group = GraphQLGroup.make(${operationNames.join(", ")})`
      )
    }

    const imports: Array<string> = []
    const graphql = [...(ctx.usesGraphQL ? ["GraphQL"] : []), ...(ctx.usesGroup ? ["GraphQLGroup"] : [])]
    if (graphql.length > 0) imports.push(`import { ${graphql.join(", ")} } from "effect/graphql"`)
    if (ctx.usesSchema) imports.push(`import * as Schema from "effect/Schema"`)
    const fragmentImports = Array.from(ctx.imports, ([path, names]) => ({
      specifier: this.options.importSpecifier(file.outputPath, path),
      names: Array.from(names).sort()
    })).sort((a, b) => a.specifier < b.specifier ? -1 : a.specifier > b.specifier ? 1 : 0)
    for (const { names, specifier } of fragmentImports) {
      imports.push(`import { ${names.join(", ")} } from ${JSON.stringify(specifier)}`)
    }
    if (ctx.usesShared) {
      imports.push(
        `import * as Shared from ${
          JSON.stringify(this.options.importSpecifier(file.outputPath, this.options.sharedPath))
        }`
      )
    }

    return {
      path: file.outputPath,
      contents: `${[header(file.sourceName), ...imports].join("\n")}\n\n${blocks.join("\n\n")}\n`
    }
  }

  emitFragment(ctx: FileContext, definition: Ast.FragmentDefinition): string {
    const name = definition.name.value
    const type = this.objectType(definition.typeCondition.name.value)
    ctx.usesSchema = true
    const description = definition.description?.value ?? type.description
    const doc = docLines([`\`fragment ${name} on ${type.name}\``], descriptionLines(description))
    const body = this.selection(ctx, type, definition.selectionSet.selections, "", true)
    return `${jsdoc(doc, "")}export class ${name} extends Schema.Opaque<${name}>()(${body}) {}`
  }

  emitOperation(ctx: FileContext, definition: Ast.OperationDefinition): string {
    const name = definition.name!.value
    const root = this.objectType(this.rootType(definition))
    ctx.usesGraphQL = true
    const doc = docLines(
      [`\`${definition.operation} ${name}\``],
      descriptionLines(definition.description?.value)
    )
    const lines = [`  document: ${JSON.stringify(this.document(definition))},`]
    if (definition.variableDefinitions.length > 0) {
      const members = definition.variableDefinitions.map((variable) => {
        const defaultValue = variable.defaultValue === undefined
          ? undefined
          : SchemaModel.fromAstConstValue(variable.defaultValue)
        const type = SchemaModel.fromAstType(variable.type)
        const expression = this.input(type, defaultValue !== undefined, (name) => this.shared(ctx, name))
        ctx.usesSchema ||= expression.includes("Schema.")
        const variableDoc = docLines(descriptionLines(variable.description?.value), defaultTag(defaultValue))
        return `${jsdoc(variableDoc, "    ")}    ${propertyKey(variable.variable.name.value)}: ${expression}`
      })
      lines.push(`  variables: {\n${members.join(",\n")}\n  },`)
    }
    lines.push(`  result: ${this.selection(ctx, root, definition.selectionSet.selections, "  ")}`)
    return [
      `${jsdoc(doc, "")}export const ${name} = GraphQL.${definition.operation}(${JSON.stringify(name)}, {`,
      ...lines,
      "})",
      `export declare namespace ${name} {`,
      `  export type Variables = typeof ${name}.variables.Type`,
      `  export type Result = typeof ${name}.result.Type`,
      "}"
    ].join("\n")
  }

  /**
   * The operation printed compactly, followed by every fragment it uses in
   * order of first use (EFF-1831 point 7).
   */
  document(operation: Ast.OperationDefinition): string {
    const used: Array<Ast.FragmentDefinition> = []
    const seen = new Set<string>()
    const collect = (selectionSet: Ast.SelectionSet): void => {
      for (const selection of selectionSet.selections) {
        if (selection._tag === "FragmentSpread") {
          if (!seen.has(selection.name.value)) {
            seen.add(selection.name.value)
            used.push(this.fragmentDefinition(selection.name.value))
          }
        } else if (selection.selectionSet !== undefined) {
          collect(selection.selectionSet)
        }
      }
    }
    collect(operation.selectionSet)
    for (let i = 0; i < used.length; i++) collect(used[i]!.selectionSet)
    return print({ _tag: "Document", definitions: [operation, ...used], loc: operation.loc })
  }

  // ---------------------------------------------------------------------------
  // Shared module
  // ---------------------------------------------------------------------------

  unmappedScalars(): ReadonlyArray<string> {
    return this.sharedNames.filter((name) => {
      const type = this.type(name)
      return type._tag === "ScalarType" && !SchemaModel.builtInScalarNames.includes(name) &&
        !this.options.scalars.has(name)
    })
  }

  emitShared(): OutputFile {
    // Close over input objects: each one reaches the types of all its fields.
    const inputs: Array<SchemaModel.InputObjectType> = []
    const all = new Set<string>()
    const visit = (name: string): void => {
      if (all.has(name)) return
      all.add(name)
      const type = this.type(name)
      if (type._tag !== "InputObjectType") return
      for (const field of type.fields) visit(SchemaModel.namedTypeOf(field.type))
      inputs.push(type)
    }
    for (const name of Array.from(this.reached).sort()) visit(name)
    all.delete("String")
    all.delete("Boolean")

    const byName = Array.from(all).sort()
    const builtIns = builtInSharedScalars.filter((name) => all.has(name))
    const scalars = byName.filter((name) =>
      this.type(name)._tag === "ScalarType" && !SchemaModel.builtInScalarNames.includes(name)
    )
    const enums = byName.flatMap((name) => {
      const type = this.type(name)
      return type._tag === "EnumType" ? [type] : []
    })
    this.sharedNames = byName

    // Each type is exported under its GraphQL name, which per-file modules read
    // as `Shared.<name>`. A name the module can't bind gets a local alias,
    // and the module's own imports take names no type uses.
    const taken = new Set<string>([...byName, "Typename"])
    const allocate = (candidate: string): string => {
      let name = candidate
      for (let i = 2; taken.has(name) || unbindable(name); i++) name = `${candidate}${i}`
      taken.add(name)
      return name
    }
    const locals = new Map<string, string>()
    for (const name of byName) {
      if (!unbindable(name)) continue
      let local = `${name}_`
      while (taken.has(local)) local = `${local}_`
      taken.add(local)
      locals.set(name, local)
    }
    const local = (name: string): string => locals.get(name) ?? name
    const schema = allocate("Schema")

    let usesSchema = false
    const modules = new Map<string, string>()
    const moduleName = (specifier: string): string => {
      if (specifier === "effect/Schema") {
        usesSchema = true
        return schema
      }
      const existing = modules.get(specifier)
      if (existing !== undefined) return existing
      const base = specifier.split("/").pop()!.replace(/\.[^.]*$/, "")
      const words = base.split(/[^A-Za-z0-9]+/).filter((word) => word.length > 0)
      let candidate = words.map((word) => word[0]!.toUpperCase() + word.slice(1)).join("")
      if (candidate === "" || /^[0-9]/.test(candidate)) candidate = "Scalars"
      const name = allocate(candidate)
      modules.set(specifier, name)
      return name
    }
    const scalarCodec = (name: string, fallback: string): string => {
      const mapping = this.options.scalars.get(name)
      if (mapping === undefined) {
        usesSchema = true
        return fallback
      }
      return `${moduleName(mapping.specifier)}.${mapping.exportName}`
    }
    /** `export const X = ...`, or a local alias exported under the GraphQL name. */
    const declare = (name: string, declaration: (binding: string) => string, typeAlias: boolean): string => {
      const binding = local(name)
      const alias = typeAlias ? `\n${binding === name ? "export " : ""}type ${binding} = typeof ${binding}.Type` : ""
      return binding === name
        ? `export ${declaration(name)}${alias}`
        : `${declaration(binding)}${alias}\nexport { ${binding} as ${name} }`
    }

    const blocks: Array<string> = []
    for (const name of [...builtIns, ...scalars]) {
      const type = this.type(name)
      const codec = scalarCodec(name, builtIns.includes(name) ? builtInScalarCodec(name, schema) : `${schema}.Json`)
      blocks.push(
        `${jsdoc(descriptionLines(type.description), "")}${declare(name, (b) => `const ${b} = ${codec}`, false)}`
      )
    }
    for (const type of enums) {
      usesSchema = true
      const values = type.values.map((value) => {
        const description = descriptionLines(value.description).join(" ")
        const deprecated = value.deprecationReason === undefined
          ? ""
          : ` Deprecated: ${value.deprecationReason.replace(/\s*\r?\n\s*/g, " ").replace(/\*\//g, "*\\/")}`
        return `- \`${value.name}\`${description === "" ? "" : `: ${description}`}${deprecated}`
      })
      const doc = docLines(descriptionLines(type.description), values)
      const literals = type.values.map((value) => JSON.stringify(value.name)).join(", ")
      blocks.push(
        `${jsdoc(doc, "")}${declare(type.name, (b) => `const ${b} = ${schema}.Literals([${literals}])`, true)}`
      )
    }
    for (const type of inputs) {
      usesSchema = true
      const members = type.fields.map((field) => {
        const doc = docLines(
          descriptionLines(field.description),
          [...deprecatedTag(field.deprecationReason), ...defaultTag(field.defaultValue)]
        )
        return `${jsdoc(doc, "  ")}  ${propertyKey(field.name)}: ${
          this.input(field.type, field.defaultValue !== undefined, local, schema)
        }`
      })
      const body = struct(members, "", schema)
      blocks.push(
        `${jsdoc(descriptionLines(type.description), "")}${
          declare(type.name, (b) => `class ${b} extends ${schema}.Opaque<${b}>()(${body}) {}`, false)
        }`
      )
    }

    const imports: Array<string> = []
    if (usesSchema) imports.push(`import * as ${schema} from "effect/Schema"`)
    for (const [specifier, name] of modules) {
      imports.push(`import * as ${name} from ${JSON.stringify(specifier)}`)
    }
    const body = blocks.length === 0 ? "export {}" : blocks.join("\n\n")
    return {
      path: this.options.sharedPath,
      contents: `${[header(undefined), ...imports].join("\n")}\n\n${body}\n`
    }
  }
}

const kindName = (type: SchemaModel.NamedType): string => {
  switch (type._tag) {
    case "InterfaceType":
      return "interface"
    case "UnionType":
      return "union"
    case "ObjectType":
      return "object type"
    case "InputObjectType":
      return "input object"
    case "EnumType":
      return "enum"
    case "ScalarType":
      return "scalar"
  }
}
